SET DEFINE OFF;

--STORED PROCEDURE: SP_TRUNC_CDC_TIME2OFFER_TABLE
CREATE OR REPLACE PROCEDURE HHS_HR.SP_TRUNC_CDC_TIME2OFFER_TABLE
AS
BEGIN
--DESCRIPTION: Truncates the CDC Time to Offer Report Table
	EXECUTE IMMEDIATE 'TRUNCATE TABLE HHS_HR.DSS_CDC_TIME_TO_OFFER_STG';
EXCEPTION
	WHEN OTHERS THEN
		SP_ERROR_LOG();
END;
/

--STORED PROCEDURE: SP_TRUNC_CDC_TIME2STAFF_TABLE
CREATE OR REPLACE PROCEDURE HHS_HR.SP_TRUNC_CDC_TIME2STAFF_TABLE
AS
BEGIN
--DESCRIPTION: Truncates the CDC Time to Staff Report Table
	EXECUTE IMMEDIATE 'TRUNCATE TABLE HHS_HR.DSS_CDC_TIME_TO_STAFF_STG';
EXCEPTION
	WHEN OTHERS THEN
		SP_ERROR_LOG();
END;
/

--STORED PROCEDURE: SP_TRUNC_CDC_CERT_TABLE
CREATE OR REPLACE PROCEDURE HHS_HR.SP_TRUNC_CDC_CERT_TABLE
AS
BEGIN
--DESCRIPTION: Truncates the CDC Certificate Report Table
	EXECUTE IMMEDIATE 'TRUNCATE TABLE HHS_HR.DSS_CDC_CERTIFICATE_STG';
EXCEPTION
	WHEN OTHERS THEN
		SP_ERROR_LOG();
END;
/

--STORED PROCEDURE: SP_TRUNC_CDC_AUDIT_TABLE
CREATE OR REPLACE PROCEDURE HHS_HR.SP_TRUNC_CDC_AUDIT_TABLE
AS
BEGIN
--DESCRIPTION: Truncates the CDC Cert Audit Report Table
	EXECUTE IMMEDIATE 'TRUNCATE TABLE HHS_HR.DSS_CDC_CERT_AUDIT_STG';
EXCEPTION
	WHEN OTHERS THEN
		SP_ERROR_LOG();
END;
/