--------------------------------------------------------
--  File created - Tuesday-March-06-2018   
--------------------------------------------------------
/*

DROP TABLE "HHS_HR"."PDAF_PII_FIELD_META";
DROP TABLE "HHS_HR"."PDAF_PII_FIELD_XML_META";
DROP TABLE "HHS_HR"."PDAF_PII_LOG";
DROP SEQUENCE PDAF_PII_RUNDEGREE_SEQ;
DROP SEQUENCE PDAF_PII_LOG_SEQ;

*/

--------------------------------------------------------
--  DDL for Table PDAF_PII_FIELD_META
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PDAF_PII_FIELD_META"
(	"VRSN" VARCHAR2(20 BYTE), 
    "GRP_ID" VARCHAR2(100 BYTE), 
    "SCHM_NM" VARCHAR2(100 BYTE), 
    "TBL_NM" VARCHAR2(100 BYTE), 
    "CLMN_NM" VARCHAR2(100 BYTE), 
    "CLMN_TP_ID" VARCHAR2(100 BYTE), 
    "CLMN_LNGTH" NUMBER(*,0), 
    "MSK_TP_ID" VARCHAR2(100 BYTE), 
    "MSK" VARCHAR2(4000 BYTE), 
    "DSBLD" CHAR(1 BYTE)
);

CREATE UNIQUE INDEX "PDAF_PII_FIELD_META_PK" ON "HHS_HR"."PDAF_PII_FIELD_META" ("VRSN", "GRP_ID", "SCHM_NM", "TBL_NM", "CLMN_NM");
  
ALTER TABLE "HHS_HR"."PDAF_PII_FIELD_META" ADD CONSTRAINT "PDAF_PII_FIELD_META_PK" PRIMARY KEY ("VRSN", "GRP_ID", "SCHM_NM", "TBL_NM", "CLMN_NM") ENABLE;
ALTER TABLE "HHS_HR"."PDAF_PII_FIELD_META" MODIFY ("VRSN" NOT NULL ENABLE);
ALTER TABLE "HHS_HR"."PDAF_PII_FIELD_META" MODIFY ("GRP_ID" NOT NULL ENABLE);
ALTER TABLE "HHS_HR"."PDAF_PII_FIELD_META" MODIFY ("SCHM_NM" NOT NULL ENABLE);
ALTER TABLE "HHS_HR"."PDAF_PII_FIELD_META" MODIFY ("TBL_NM" NOT NULL ENABLE);
ALTER TABLE "HHS_HR"."PDAF_PII_FIELD_META" MODIFY ("CLMN_NM" NOT NULL ENABLE);
/

--------------------------------------------------------
--  DDL for Table PDAF_PII_FIELD_XML_META
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PDAF_PII_FIELD_XML_META"
(	"VRSN" VARCHAR2(20 BYTE), 
    "GRP_ID" VARCHAR2(100 BYTE), 
    "SCHM_NM" VARCHAR2(100 BYTE), 
    "TBL_NM" VARCHAR2(100 BYTE), 
    "CLMN_NM" VARCHAR2(100 BYTE), 
    "XPATH" VARCHAR2(4000 BYTE), 
    "MSK_TP_ID" VARCHAR2(100 BYTE), 
    "MSK" VARCHAR2(4000 BYTE)
);

CREATE UNIQUE INDEX "PDAF_PII_FIELD_XML_META_PK" ON "HHS_HR"."PDAF_PII_FIELD_XML_META" ("VRSN", "GRP_ID", "SCHM_NM", "TBL_NM", "CLMN_NM", "XPATH");
  
ALTER TABLE "HHS_HR"."PDAF_PII_FIELD_XML_META" ADD CONSTRAINT "PDAF_PII_FIELD_XML_META_PK" PRIMARY KEY ("VRSN", "GRP_ID", "SCHM_NM", "TBL_NM", "CLMN_NM", "XPATH") ENABLE;

ALTER TABLE "HHS_HR"."PDAF_PII_FIELD_XML_META" MODIFY ("VRSN" NOT NULL ENABLE);
ALTER TABLE "HHS_HR"."PDAF_PII_FIELD_XML_META" MODIFY ("GRP_ID" NOT NULL ENABLE); 
ALTER TABLE "HHS_HR"."PDAF_PII_FIELD_XML_META" MODIFY ("SCHM_NM" NOT NULL ENABLE);
ALTER TABLE "HHS_HR"."PDAF_PII_FIELD_XML_META" MODIFY ("TBL_NM" NOT NULL ENABLE);
ALTER TABLE "HHS_HR"."PDAF_PII_FIELD_XML_META" MODIFY ("CLMN_NM" NOT NULL ENABLE);
ALTER TABLE "HHS_HR"."PDAF_PII_FIELD_XML_META" MODIFY ("XPATH" NOT NULL ENABLE);
/

CREATE SEQUENCE "HHS_HR"."PDAF_PII_RUNDEGREE_SEQ"
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;
/

CREATE SEQUENCE "HHS_HR"."PDAF_PII_LOG_SEQ"
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;
/

--------------------------------------------------------
--  DDL for Table PDAF_PII_LOG
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PDAF_PII_LOG" 
( 
    -- "SEQNO" NUMBER(38) default PDAF_PII_LOG_SEQ.nextval, -- Oracle 12c or later version
    "SEQNO" NUMBER(38),
    "RUNDEGREE" VARCHAR2(20 BYTE), 
    "VRSN" VARCHAR2(20 BYTE), 
    "GRP_ID" VARCHAR2(100 BYTE), 
    "SCHM_NM" VARCHAR2(100 BYTE), 
    "TBL_NM" VARCHAR2(100 BYTE), 
    "CLMN_NM" VARCHAR2(100 BYTE), 
    "XPATH" VARCHAR2(4000 BYTE), 
    "MSK_TP_ID" VARCHAR2(100 BYTE), 
    "MSK" VARCHAR2(4000 BYTE), 
    "LOG" VARCHAR2(4000 BYTE)
);

CREATE UNIQUE INDEX "HHS_HR"."PDAF_PII_LOG_PK" ON "HHS_HR"."PDAF_PII_LOG" ("SEQNO"); 

ALTER TABLE "HHS_HR"."PDAF_PII_LOG" ADD CONSTRAINT "PDAF_PII_LOG_PK" PRIMARY KEY ("SEQNO") ENABLE;
 
/


