-- Log in as SYSTEM, SYSDBA

DROP ROLE HHS_HR_PDAF_ROLE;

CREATE ROLE HHS_HR_PDAF_ROLE;

-- Previlege for PDAF role
GRANT ALTER SESSION, CREATE CLUSTER, CREATE DATABASE LINK
		, CREATE SEQUENCE, CREATE SESSION, CREATE SYNONYM, CREATE TABLE
		, CREATE VIEW, CREATE PROCEDURE
	TO HHS_HR_PDAF_ROLE;
    
-- PDAF's HHS_HR tables access
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_HR.PDAF_PII_FIELD_META TO HHS_HR_PDAF_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_HR.PDAF_PII_FIELD_XML_META TO HHS_HR_PDAF_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_HR.PDAF_PII_LOG TO HHS_HR_PDAF_ROLE;

-- PDAF's HHS_CDC_HR tables access
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.TBL_FORM_DTL TO HHS_HR_PDAF_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.TBL_FORM_DTL_AUDIT TO HHS_HR_PDAF_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.TBL_LOOKUP TO HHS_HR_PDAF_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.EXTERNAL_LINK_LOOKUP TO HHS_HR_PDAF_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ERROR_LOG TO HHS_HR_PDAF_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CDC_HR.ADMINISTRATIVE_CODE TO HHS_HR_PDAF_ROLE;

-- PDAF's HHS_CMS_HR tables access

-- PDAF's HHS_IHS_HR tables access

-- PDAF's HHS_WHRSC_HR tables access

-- PDAF's sequence access
GRANT SELECT on HHS_HR.PDAF_PII_RUNDEGREE_SEQ to HHS_HR_PDAF_ROLE;
GRANT SELECT on HHS_HR.PDAF_PII_LOG_SEQ to HHS_HR_PDAF_ROLE;

-- privilege for HHS_HR_RW_ROLE
GRANT HHS_HR_PDAF_ROLE TO HHS_HR;
GRANT HHS_HR_PDAF_ROLE TO HHS_CDC_HR;

/
