
-- Log in as SYSTEM, SYSDBA

-- PDAF's package access
GRANT EXECUTE ON HHS_HR.BFPS_DATAMASK TO HHS_HR_PDAF_ROLE;
GRANT EXECUTE ON HHS_HR.BFPS_PDAF TO HHS_HR_PDAF_ROLE;

--GRANT EXECUTE ON HHS_HR.BIZFLOWDATAMASK TO HHS_CDC_HR;
--GRANT EXECUTE ON HHS_HR.BIZFLOWPDAF TO HHS_CDC_HR;

-- privilege for HHS_HR_RW_ROLE
GRANT HHS_HR_PDAF_ROLE TO HHS_HR;
GRANT HHS_HR_PDAF_ROLE TO HHS_CDC_HR;

/

