create or replace PROCEDURE        SP_CMS_POSSESS_STG2FNL
IS
	V_STG_CNT                   NUMBER;
	V_ERRCODE                   NUMBER(10);
	V_ERRMSG                    VARCHAR2(512);
    LAST_RUN                    VARCHAR(200);
	CURSOR CUR_POSS_STG
	IS
		SELECT REQUEST_NUMBER
    		, REQUEST_APPROVAL_DATE
    		, ANNOUNCEMENT_NUMBER
    		, HM_ANN_RVW_SENT_DATE
    		, HM_ANN_RVW_CMPL_DATE
    		, ANNOUNCEMENT_OPEN_DATE
    		, ANNOUNCEMENT_CLOSE_DATE
    		, CERTIFICATE_NUMBER
    		, CERTIFICATE_ISSUE_DATE
    		, REVIEW_SENT_DATE
    		, REVIEW_RETURN_DATE
    		, INITIAL_AUDIT_DATE   
    		, NEW_HIRE_CREATE_DATE
    		, SEND_TENT_OFFR_CMPL_DATE
    		, TENT_OFFR_RSPNS_DATE
    		, RCVE_BKGRND_INVST_DATE
    		, EOD_DATE
    		, SEND_OFCL_OFFR_CMPL_DATE
    		, INIT_BKGRND_INVST_DATE
    		, REQUEST_TYPE
    		, REQUEST_STATUS
    		, REQUEST_CREATE_DATE
    		, ARRVL_VERIF_CMPL_DATE
		FROM HHS_HR.DSS_CMS_TIME_OF_POSSESS_STG;

		TYPE TYPE_POSS_STG IS TABLE OF CUR_POSS_STG%ROWTYPE
			INDEX BY PLS_INTEGER;

		V_TBL_POSS_STG TYPE_POSS_STG;
BEGIN
	BEGIN
		SELECT COUNT(*)
		INTO V_STG_CNT
		FROM HHS_HR.DSS_CMS_TIME_OF_POSSESS_STG;
		
        --FIND LAST RUN TIME
        SELECT COUNT(*) INTO  LAST_RUN FROM batch_step_execution WHERE TO_CHAR(START_TIME,'DD-MM-YY') = TO_CHAR(SYSDATE,'DD-MM-YY')
            AND step_name IN('executeCMSPossessRecruitmentReportStep','executeCMSPossessApptmntReportStep');
    
		IF V_STG_CNT > 0 THEN
            IF LAST_RUN = 0 THEN
                EXECUTE IMMEDIATE 'TRUNCATE TABLE DSS_CMS_TIME_OF_POSSESS';
            END IF;
			OPEN CUR_POSS_STG;
			LOOP
				FETCH CUR_POSS_STG
				BULK COLLECT INTO V_TBL_POSS_STG
				LIMIT 1000;
				
				FORALL i IN V_TBL_POSS_STG.FIRST..V_TBL_POSS_STG.LAST SAVE EXCEPTIONS
					INSERT INTO DSS_CMS_TIME_OF_POSSESS VALUES V_TBL_POSS_STG(i);
				COMMIT;
				
				EXIT WHEN CUR_POSS_STG%NOTFOUND;
			END LOOP;
			CLOSE CUR_POSS_STG;
		END IF;
	EXCEPTION
		WHEN OTHERS THEN
			SP_ERROR_LOG();
			V_ERRCODE := SQLCODE;
			V_ERRMSG := SQLERRM;
		--DBMS_OUTPUT.PUT_LINE('ERROR occurred while executing SP_CMS_POSSESS_STG2FNL -------------------');
		--DBMS_OUTPUT.PUT_LINE('Error code    = ' || V_ERRCODE);
		--DBMS_OUTPUT.PUT_LINE('Error message = ' || V_ERRMSG);
	END;
	--DBMS_OUTPUT.PUT_LINE('SP_CMS_POSSESS_STG2FNL - END ==========================');
EXCEPTION
	WHEN OTHERS THEN
		SP_ERROR_LOG();
		V_ERRCODE := SQLCODE;
		V_ERRMSG := SQLERRM;
		--DBMS_OUTPUT.PUT_LINE('ERROR occurred while executing SP_CMS_POSSESS_STG2FNL -------------------');
		--DBMS_OUTPUT.PUT_LINE('Error code    = ' || V_ERRCODE);
		--DBMS_OUTPUT.PUT_LINE('Error message = ' || V_ERRMSG);
END;