create or replace PROCEDURE        SP_TRUNC_CMS_POSSESS_TABLE
AS
LAST_RUN    NUMBER;
BEGIN
--DESCRIPTION: Truncates the CMS Time of Possession Table
	SELECT COUNT(*) INTO  LAST_RUN FROM batch_step_execution WHERE TO_CHAR(START_TIME,'DD-MM-YY') = TO_CHAR(SYSDATE,'DD-MM-YY')
    AND step_name IN('executeCMSPossessReportStep','executeCMSPossessApptmntReportStep');
    
    IF LAST_RUN = 0 THEN --FOR RE-USING SAME PROCEDURES BETWEEN TOP RECRUITMENT AND APPOINTMENT
        EXECUTE IMMEDIATE 'TRUNCATE TABLE HHS_HR.DSS_CMS_TIME_OF_POSSESS_STG';
    END IF;
EXCEPTION
	WHEN OTHERS THEN
		SP_ERROR_LOG();
END;