SET DEFINE OFF;

UPDATE HHS_HR.HHS_LIST_MANAGER_LOOKUP SET LOOKUP_DESCRIPTION = '0 - None' WHERE LOOKUP_NAME = 'Tenure_Code' AND LOOKUP_CODE = '0';
UPDATE HHS_HR.HHS_LIST_MANAGER_LOOKUP SET LOOKUP_DESCRIPTION = '1 - Permanent (Career)' WHERE LOOKUP_NAME = 'Tenure_Code' AND LOOKUP_CODE = '1';
UPDATE HHS_HR.HHS_LIST_MANAGER_LOOKUP SET LOOKUP_DESCRIPTION = '2 - Conditional (Career Conditional)' WHERE LOOKUP_NAME = 'Tenure_Code' AND LOOKUP_CODE = '2';
UPDATE HHS_HR.HHS_LIST_MANAGER_LOOKUP SET LOOKUP_DESCRIPTION = '3 - Indefinite' WHERE LOOKUP_NAME = 'Tenure_Code' AND LOOKUP_CODE = '3';

commit;
