CREATE OR REPLACE FUNCTION BIZFLOW.HHS_FN_SUBTRACT_BUSDAY(
	I_STARTDATE             IN      DATE
	, I_DAYS                IN      INT
)
RETURN DATE
IS
	V_DAY DATE;
	V_DAYS_CNT INT := I_DAYS;

	CURSOR CUR_BUSDAY IS
	SELECT MIN(CALDTIME)
	FROM BIZFLOW.CAL C
		INNER JOIN BIZFLOW.CALHEAD CH
			ON CH.DAYOFWEEK = C.DAYOFWEEK
	WHERE CH.DAYTYPE <> 'H'
		AND C.CALDTIME NOT IN (SELECT CALDTIME FROM BIZFLOW.MEMBERCAL WHERE DAYTYPE = 'H' AND MEMBERID = '0000000000')
		AND CH.MEMBERID = '0000000000'
		AND C.CALDTIME = (I_STARTDATE - V_DAYS_CNT);
	
BEGIN

	IF I_STARTDATE IS NULL THEN
	
		RETURN I_STARTDATE;
		
	ELSE 
	
		WHILE V_DAY IS NULL LOOP
	
			OPEN CUR_BUSDAY;
			FETCH CUR_BUSDAY INTO V_DAY;
			EXIT WHEN CUR_BUSDAY%NOTFOUND;
			CLOSE CUR_BUSDAY;
			
			V_DAYS_CNT := V_DAYS_CNT + 1;
			
		END LOOP;
	
		RETURN V_DAY;
		
	END IF;
END;
/