
----------------------------------
-- grant for HHS_HR_RW_ROLE
----------------------------------

GRANT EXECUTE ON HHS_HR.SP_UPDATE_INTG_DATA TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_ANNOUNCEMENT_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_APPLICATION_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_CERTIFICATE_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_NEWHIRE_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_REQUEST_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_REVIEW_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_TASK_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_VACANCY_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_TIME2OFFER_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_TIME2STAFF_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_IHS_VAC_TABLE TO HHS_HR_RW_ROLE;

----------------------------------
-- grant for HHS_HR_DEV_ROLE
----------------------------------

GRANT EXECUTE ON HHS_HR.SP_UPDATE_INTG_DATA TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_ANNOUNCEMENT_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_APPLICATION_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_CERTIFICATE_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_NEWHIRE_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_REQUEST_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_REVIEW_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_TASK_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_VACANCY_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_TIME2OFFER_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_TIME2STAFF_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_UPDATE_IHS_VAC_TABLE TO HHS_HR_DEV_ROLE;