SET DEFINE OFF;

DELETE HHS_HR.HHS_LIST_MANAGER_LOOKUP WHERE LOOKUP_NAME ='OPDIV_STAFF_DIV';

Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('OPDIV_STAFF_DIV','Centers for Disease Control and Prevention','CDC','PCP',null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('OPDIV_STAFF_DIV','Centers for Medicare & Medicaid Services','CMS','PCP',null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('OPDIV_STAFF_DIV','Food and Drug Administration','FDA','PCP',null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('OPDIV_STAFF_DIV','HHS at large','HHS at large','PPP',null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('OPDIV_STAFF_DIV','Health Resources and Services Administration','HRSA','PCP',null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('OPDIV_STAFF_DIV','Indian Health Service','IHS','PCP',null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('OPDIV_STAFF_DIV','National Institutes of Health','NIH','PCP',null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('OPDIV_STAFF_DIV','Office of Inspector General','OIG','PCP',null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('OPDIV_STAFF_DIV','Office of Medicare Hearings and Appeals','OMHA','PCP',null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('OPDIV_STAFF_DIV','Washington HR Services Center','WHRSC','PCP',null,null);


DELETE HHS_HR.HHS_LIST_MANAGER_LOOKUP WHERE LOOKUP_NAME ='Performance Rating';

Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Performance Rating','Unacceptable Fail Level','1',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Performance Rating','Between success and unacceptable','2',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Performance Rating','Fully successful or equivalent','3',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Performance Rating','Between outstanding and success','4',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Performance Rating','Outstanding or equivalent','5',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Performance Rating','Not Rated','X',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Performance Rating','Exclusion','Z',null,null,null);


commit;
