
----------------------------------
-- grant for HHS_HR_RW_ROLE
----------------------------------

GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.LIST_SEARCH_CANDIDATE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.FN_GET_DISTANCE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.FN_GET_SEARCH_ID TO HHS_HR_RW_ROLE;
