SET DEFINE OFF;

DROP TABLE LIST_SEARCH_CANDIDATE CASCADE CONSTRAINTS ;
DROP SEQUENCE LIST_SEARCH_CANDIDATE_SEQ;



--------------------------------------------------------
--  DDL for Table LIST_SEARCH_CANDIDATE
--------------------------------------------------------

CREATE TABLE LIST_SEARCH_CANDIDATE 
(
	ID	NUMBER (10),
	SEARCH_ID  NUMBER (10),
	CANDIDATE_ID NUMBER (15),
	LIST_ID NUMBER(15),
	CLEARING_ACTION_CODE VARCHAR2(100),
	COMMENTS VARCHAR2(1000),
	JOB_OPENING_ID VARCHAR2(30),
	PAY_PLAN VARCHAR2(20),
	OCC_SERIES   VARCHAR2 (8),
	GRADE_CODE  VARCHAR2 (2),
	EMAIL_SENT_TO_CANDIDATE_DATE DATE,
	ELIGIBILITY_END_REASON_CODE  VARCHAR2(60),
	LAST_UPDATED_BY VARCHAR2(10),
	LAST_UPDATE_DATE DATE,
	CREATED_BY VARCHAR2(10),
	CREATION_DATE DATE
) ;

--------------------------------------------------------
--  DDL for Index LIST_SEARCH_CANDIDATE_INDEX
--------------------------------------------------------

CREATE UNIQUE INDEX LIST_SEARCH_CANDIDATE_INDEX ON LIST_SEARCH_CANDIDATE(ID);

--------------------------------------------------------
--  Constraints for Table LIST_SEARCH_CANDIDATE
--------------------------------------------------------

--ALTER TABLE LIST_SEARCH_CANDIDATE ADD UNIQUE (CANDIDATE_ID);
ALTER TABLE LIST_SEARCH_CANDIDATE MODIFY (SEARCH_ID NOT NULL );
ALTER TABLE LIST_SEARCH_CANDIDATE MODIFY (ID NOT NULL );
ALTER TABLE LIST_SEARCH_CANDIDATE MODIFY (CANDIDATE_ID NOT NULL );
ALTER TABLE LIST_SEARCH_CANDIDATE MODIFY (LIST_ID NOT NULL );




--------------------------------------------------------
--  Ref Constraints for Table LIST_SEARCH_CANDIDATE
--------------------------------------------------------

--ALTER TABLE LIST_SEARCH_CANDIDATE ADD FOREIGN KEY (CANDIDATE_ID) REFERENCES CANDIDATE (CANDIDATE_ID) ;

--------------------------------------------------------
--  DDL for SEQLUENCE LIST_SEARCH_CANDIDATE_SEQ
--------------------------------------------------------

CREATE SEQUENCE LIST_SEARCH_CANDIDATE_SEQ
	INCREMENT BY 1
	START WITH 1000000000
	NOMAXVALUE
	NOCYCLE
	NOCACHE;

/

--------------------------------------------------------
--  DDL for TRIGER LIST_TRG
--------------------------------------------------------

CREATE OR REPLACE TRIGGER LIST_SEARCH_CANDIDATE_TRG
BEFORE INSERT ON LIST_SEARCH_CANDIDATE
FOR EACH ROW
BEGIN
	SELECT LIST_SEARCH_CANDIDATE_SEQ.NEXTVAL
	INTO :NEW.ID
	FROM DUAL;
END;

/






	
