SET DEFINE OFF;

Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Reason Cleared','Other','Other',null,null,null);

commit;
