----------------------------------
-- grant for HHS_HR_RW_ROLE
----------------------------------
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_OFFER TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_STAFF TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_OFFER_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_STAFF_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_CERTIFICATE TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_CERTIFICATE_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_CERT_AUDIT TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_CERT_AUDIT_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_ANNOUNCEMENT TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_ANNOUNCEMENT_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_TIME_OF_POSSESS TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_TIME_OF_POSSESS_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_TIME_TO_HIRE TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_TIME_TO_HIRE_STG TO HHS_HR_RW_ROLE;

----------------------------------
-- grant for HHS_HR_DEV_ROLE
----------------------------------
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_OFFER TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_STAFF TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_OFFER_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_STAFF_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_CERTIFICATE TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_CERTIFICATE_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_CERT_AUDIT TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_CERT_AUDIT_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_ANNOUNCEMENT TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_ANNOUNCEMENT_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_TIME_OF_POSSESS TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_TIME_OF_POSSESS_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_TIME_TO_HIRE TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_TIME_TO_HIRE_STG TO HHS_HR_DEV_ROLE;