SET DEFINE OFF;

DELETE HHS_HR.HHS_LIST_MANAGER_LOOKUP WHERE LOOKUP_NAME ='Performance Rating';
DELETE HHS_HR.HHS_LIST_MANAGER_LOOKUP WHERE LOOKUP_NAME ='Veteran Status';

Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Performance Rating','Unsatisfactory','1',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Performance Rating','Minimally Satisfactory','2',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Performance Rating','Fully Successful','3',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Performance Rating','Exceeds Fully Successful','4',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Performance Rating','Outstanding','5',null,null,null);

Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Position_Occupied','Competitive','1',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Position_Occupied','Excepted','2',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Position_Occupied','SES General','3',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Position_Occupied','SES Career Reserved','4',null,null,null);

Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Tenure_Code','Senior Executive Service or Presidential appointment subject to Senate confirmation','0',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Tenure_Code','Permanent career employee with 3 or more years of service','1',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Tenure_Code','Career-conditional employee, less than 3 years of service or still on probation','2',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Tenure_Code','Temporary or term appointment','3',null,null,null);

Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Veteran Status','None','1',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Veteran Status','5-point','2',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Veteran Status','10-point/disability','3',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Veteran Status','10-POINT/COMPENSABLE','4',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Veteran Status','10-point/other','5',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Veteran Status','10-point/compensable/30 percent','6',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values ('Veteran Status','Sole Survivorship Preference','7',null,null,null);

Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'AL',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'AR',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'AZ',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'CA',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'CO',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'CT',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'DC',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'DE',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'FL',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'GA',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'HI',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'IA',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'ID',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'IL',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'IN',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'KS',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'KY',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'LA',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'MA',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'MD',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'ME',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'MI',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'MN',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'MO',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'MS',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'MT',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'NC',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'ND',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'NE',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'NH',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'NJ',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'NM',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'NV',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'NY',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'OH',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'OK',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'OR',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'PA',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'RI',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'SC',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'SD',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'TN',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'TX',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'UT',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'VA',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'VT',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'WA',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'WI',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'WV',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('stateList',null,'WY',null,null,null);

Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndCTAP',null,'Separates from HHS either voluntarily or involuntarily',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndCTAP',null,'Selected for position within HHS',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndCTAP',null,'Receives a notice rescinding, canceling, or modifying the notice',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndCTAP',null,'Is placed in another position within HHS',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndCTAP',null,'Is appointed to a career, career-conditional or excepted appointment without time limit in any agency at any grade or pay level',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndCTAP',null,'Does not meet required qualification standards',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndCTAP',null,'Did not apply to announcement',null,null,null);

Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndRPL',null,'Declines or fails to reply to HHS’ inquiry about an offer or scheduled interview',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndRPL',null,'Selected for position within HHS',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndRPL',null,'Receives a written cancellation, rescission or modification',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndRPL',null,'Voluntarily separates from HHS',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndRPL',null,'At applicant’s request',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndRPL',null,'Placed in a position without time limit at any grade or pay level within HHS',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndRPL',null,'Leaves the area covered by an overseas RPL (5CFR301)',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndRPL',null,'Does not meet required qualification standards',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndRPL',null,'Did not apply to announcement',null,null,null);

Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndPRL',null,'Declines or fails to reply to HHS’ inquiry about an offer or scheduled interview',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndPRL',null,'Selected for position within HHS',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndPRL',null,'Receives a written cancellation, rescission or modification',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndPRL',null,'Voluntarily separates from HHS',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndPRL',null,'At applicant’s request',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndPRL',null,'Placed in a position without time limit at any grade or pay level within HHS',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndPRL',null,'Does not meet required qualification standards',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndPRL',null,'Did not apply to announcement',null,null,null);

Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndOTHER',null,'Does not meet required qualification standards',null,null,null);
Insert into HHS_HR.HHS_LIST_MANAGER_LOOKUP (LOOKUP_NAME,LOOKUP_DESCRIPTION,LOOKUP_CODE,CONDITION_1,CONDITION_2,DISP_ORDER) values('listendReasonEndOTHER',null,'Did not apply to announcement',null,null,null);

commit;
