
----------------------------------
-- grant for HHS_HR_RW_ROLE
----------------------------------
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_REQUESTS TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_REQUESTS_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_TIME_OF_POSSESS TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_TIME_OF_POSSESS_STG TO HHS_HR_RW_ROLE;

----------------------------------
-- grant for HHS_HR_DEV_ROLE
----------------------------------
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_REQUESTS TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_REQUESTS_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_TIME_OF_POSSESS TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CMS_TIME_OF_POSSESS_STG TO HHS_HR_DEV_ROLE;