
----------------------------------
-- grant for HHS_HR_RW_ROLE
----------------------------------

GRANT EXECUTE ON HHS_HR.SP_TRUNC_APPLICATION_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_ANNOUNCEMENT_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_CERTIFICATE_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_NEWHIRE_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_REQUEST_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_REVIEW_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_TASK_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_VACANCY_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_TIME2OFFER_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_TIME2STAFF_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_IHS_VAC_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_CDC_TIME2OFFER_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_CDC_TIME2STAFF_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_CDC_CERT_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_CDC_AUDIT_TABLE TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_CDC_ANN_TABLE TO HHS_HR_RW_ROLE;

----------------------------------
-- grant for HHS_HR_DEV_ROLE
----------------------------------

GRANT EXECUTE ON HHS_HR.SP_TRUNC_APPLICATION_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_ANNOUNCEMENT_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_CERTIFICATE_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_NEWHIRE_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_REQUEST_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_REVIEW_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_TASK_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_VACANCY_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_TIME2OFFER_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_TIME2STAFF_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_IHS_VAC_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_CDC_TIME2OFFER_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_CDC_TIME2STAFF_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_CDC_CERT_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_CDC_AUDIT_TABLE TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TRUNC_CDC_ANN_TABLE TO HHS_HR_DEV_ROLE;
