--------------------------------------------
-- Backout statement
--------------------------------------------
/*
DROP TABLE HHS_HR.MEMBERSTG;
DROP TABLE HHS_HR.MEMBERHISTORY;
DROP SEQUENCE HHS_HR.MEMBERHISTORY_SEQ;
DROP TABLE HHS_HR.EMPLOYEE_LOOKUP;
DROP TABLE HHS_HR.ADMINISTRATIVE_CODE;
DROP TABLE HHS_HR.APPOINTMENT_TYPE;
DROP TABLE HHS_HR.CYBERSECURITY_CODE;
DROP TABLE HHS_HR.DUTY_STATION;
DROP TABLE HHS_HR.LEGAL_AUTHORITY;
DROP TABLE HHS_HR.NATURE_OF_ACTION;
DROP TABLE HHS_HR.PAY_PLAN;
DROP TABLE HHS_HR.OCCUPATIONAL_SERIES;
DROP TABLE HHS_HR.PS_DEPT_TBL;
DROP TABLE HHS_HR.PS_HE_EWIT_DEPT_1;
DROP TABLE HHS_HR.PS_HE_RECRUIT_EWIT;
DROP TABLE HHS_HR.PS_HRS_JO_LOC;
DROP TABLE HHS_HR.PS_HRS_JO_NAME;
DROP TABLE HHS_HR.PS_HRS_JO_POSN;
DROP TABLE HHS_HR.PS_HRS_JO_RPL;
DROP TABLE HHS_HR.PS_HRS_JO_RQMT;
DROP TABLE HHS_HR.PS_HRS_JOB_OPENING;
DROP TABLE HHS_HR.PS_HRS_LOCATION_I;
DROP TABLE HHS_HR.PS_JOBCODE_TBL;
DROP TABLE HHS_HR.PS_PERSONAL_DATA_VW;
DROP TABLE HHS_HR.PS_POSITION_DATA;
DROP TABLE HHS_HR.PS_SAL_GRADE_TBL;
*/

SET DEFINE OFF;

--------------------------------------------------------
-- DDL for Table MEMBERSTG
--------------------------------------------------------
    CREATE TABLE HHS_HR.MEMBERSTG
    (HHSID          VARCHAR2(64),
    FIRSTNAME       VARCHAR2(150),
    MIDDLENAME      VARCHAR2(80),
    LASTNAME        VARCHAR2(150),
    EMAIL           VARCHAR2(256),
    DEPTNAME        VARCHAR2(8),
    LASTUPDATE      DATE
    );

    COMMENT ON TABLE HHS_HR.MEMBERSTG IS 'Member Staging table';
    COMMENT ON COLUMN HHS_HR.MEMBERSTG.HHSID IS 'HHSID of the employee';
    COMMENT ON COLUMN HHS_HR.MEMBERSTG.FIRSTNAME IS 'The first name of the employee';
    COMMENT ON COLUMN HHS_HR.MEMBERSTG.MIDDLENAME IS 'The middle name of the employee';
    COMMENT ON COLUMN HHS_HR.MEMBERSTG.LASTNAME IS 'The last name of the employee';
    COMMENT ON COLUMN HHS_HR.MEMBERSTG.EMAIL IS 'The email address of the employee';
    COMMENT ON COLUMN HHS_HR.MEMBERSTG.DEPTNAME IS 'The department name (OpDiv) of the employee';
    COMMENT ON COLUMN HHS_HR.MEMBERSTG.LASTUPDATE IS 'The last update time from the Person System';
    
--------------------------------------------------------  
--DDL for Table MEMBERHISTORY
--------------------------------------------------------  
    CREATE TABLE HHS_HR.MEMBERHISTORY
    (HISTORYID      NUMBER(38),
    CHANGEDATE      DATE,
    MEMBERID        VARCHAR2(10),
    HHSID           VARCHAR2(10),
    OPDIV           VARCHAR2(8),
    DMLTYPE         VARCHAR2(10),
    FIELDCHANGED    VARCHAR2(30),
    OLDVALUE        VARCHAR2(100),
    NEWVALUE        VARCHAR2(100)
    );
 
   COMMENT ON TABLE HHS_HR.MEMBERHISTORY IS 'Provides historical information on the transactions of the Bizflow MEMBER table';
   COMMENT ON COLUMN HHS_HR.MEMBERHISTORY.HISTORYID IS 'The unique memberhistory ID';
   COMMENT ON COLUMN HHS_HR.MEMBERHISTORY.CHANGEDATE IS 'The date that the transaction took place on the Bizflow MEMBER table';
   COMMENT ON COLUMN HHS_HR.MEMBERHISTORY.MEMBERID IS 'Corresponds to the memberid on the BizFlow MEMBER and MEMBERINFO tables';
   COMMENT ON COLUMN HHS_HR.MEMBERHISTORY.HHSID IS 'The HHS ID of the employee';
   COMMENT ON COLUMN HHS_HR.MEMBERHISTORY.OPDIV IS 'The Operating Division of the employee';
   COMMENT ON COLUMN HHS_HR.MEMBERHISTORY.DMLTYPE IS 'The type of DML: ''INSERT'' or ''UPDATE''';
   COMMENT ON COLUMN HHS_HR.MEMBERHISTORY.FIELDCHANGED IS 'The field that was updated on the Bizflow MEMBER table';
   COMMENT ON COLUMN HHS_HR.MEMBERHISTORY.OLDVALUE IS 'The old value on the Bizflow MEMBER table';
   COMMENT ON COLUMN HHS_HR.MEMBERHISTORY.NEWVALUE IS 'The new value on the Bizflow MEMBER table';
   
--------------------------------------------------------
--  DDL for Index MEMBERHISTORY_PK
--------------------------------------------------------
    CREATE UNIQUE INDEX HHS_HR.MEMBERHISTORY_PK ON HHS_HR.MEMBERHISTORY (HISTORYID);

--------------------------------------------------------
--  DDL for Index MEMBERHISTORY_I1
--------------------------------------------------------
    CREATE INDEX HHS_HR.MEMBERHISTORY_I1 ON HHS_HR.MEMBERHISTORY(HHSID);

--------------------------------------------------------  
-- DDL for Sequence MEMBERHISTORY_SEQ
--------------------------------------------------------  
    CREATE SEQUENCE HHS_HR.MEMBERHISTORY_SEQ nocache;


--------------------------------------------------------  
--  DDL for Trigger MEMBERHISTORY_TRG
--------------------------------------------------------  
    CREATE OR REPLACE TRIGGER HHS_HR.MEMBERHISTORY_TRG
    BEFORE INSERT ON HHS_HR.MEMBERHISTORY
    FOR EACH ROW
    BEGIN
        <<COLUMN_SEQUENCES>>
        BEGIN
            IF INSERTING AND :NEW.HISTORYID IS NULL THEN
                SELECT HHS_HR.MEMBERHISTORY_SEQ.NEXTVAL INTO :NEW.HISTORYID FROM SYS.DUAL;
            END IF;
        END COLUMN_SEQUENCES;
    END;
    /
    ALTER TRIGGER HHS_HR.MEMBERHISTORY_TRG ENABLE;
    
--------------------------------------------------------
-- Constraints for Table MEMBERHISTORY
-------------------------------------------------------- 
    ALTER TABLE HHS_HR.MEMBERHISTORY ADD CONSTRAINT MEMBERHISTORY_PK PRIMARY KEY (HISTORYID) ENABLE;
    ALTER TABLE HHS_HR.MEMBERHISTORY MODIFY (HISTORYID NOT NULL ENABLE);
    ALTER TABLE HHS_HR.MEMBERHISTORY MODIFY (CHANGEDATE NOT NULL ENABLE);
    ALTER TABLE HHS_HR.MEMBERHISTORY MODIFY (MEMBERID NOT NULL ENABLE);
    
    
--------------------------------------------------------
-- DDL for Table EMPLOYEE_LOOKUP
--------------------------------------------------------
    CREATE TABLE HHS_HR.EMPLOYEE_LOOKUP
    (LAST_NAME                      VARCHAR2(150),
    FIRST_NAME                      VARCHAR2(150),
    MIDDLE_NAME                     VARCHAR2(80),
    EMAIL_ADDR                      VARCHAR2(256),
    HHSID                           VARCHAR2(64),
    USERTYPE                        VARCHAR2(100),
    PIV_CARD_STATUS                 VARCHAR2(64),
    SCMS_STATUS                     VARCHAR2(64),
    EMPLID                          VARCHAR2(50),
    PAY_PLAN                        VARCHAR2(20),
    GRADE                           VARCHAR2(2),
    POSITION_TITLE_NAME             VARCHAR2(255),
    SERIES                          VARCHAR2(10),
    BARG_UNIT                       VARCHAR2(4),
    OPDIV                           VARCHAR2(100),
    ORG_CD                          VARCHAR2(50),
    PAY_BASIS                       VARCHAR2(2),
    STEP                            VARCHAR2(2),
    BASIC_PAY                       NUMBER(10,2),
    ADJ_BASIC_PAY                   NUMBER(10,2),
    CAN_CD                          VARCHAR2(50),
    JOB_CODE                        VARCHAR2(50),
    POSITION_NUM                    VARCHAR2(50),
    EMP_STATUS_FROM_PERS_SYSTEM     VARCHAR2(50),
    LAST_UPDT_FROM_PERS_SYSTEM_DT   DATE
    );

--------------------------------------------------------
--  DDL for Table ADMINISTRATIVE_CODE
--------------------------------------------------------
CREATE TABLE HHS_HR.ADMINISTRATIVE_CODE
(
	ADMIN_CODE              VARCHAR2(15),
	ADMIN_CODE_DESC         VARCHAR2(72),
	OPDIV                   VARCHAR2(8),
	OPDIV_NAME              VARCHAR2(72),
	STAFFDIV                VARCHAR2(4),
	STAFFDIV_NAME           VARCHAR2(72),
	DATE_CREATED            DATE,
	LAST_UPDATE_DATE        DATE,
	EEOC_OPDIV              VARCHAR2(20),
	ARCHIVE_IND             VARCHAR2(1)
);

--------------------------------------------------------
--  DDL for Table APPOINTMENT_TYPE
--------------------------------------------------------
CREATE TABLE HHS_HR.APPOINTMENT_TYPE
(
	APPMNT_CD          VARCHAR2(20),
	DESCRIPTION        VARCHAR2(80)
);

--------------------------------------------------------
--  DDL for Table CYBERSECURITY_CODE
--------------------------------------------------------

CREATE TABLE HHS_HR.CYBERSECURITY_CODE
(
	CYBERSECURITY_CODE           VARCHAR2(2),
	CYBERSECURITY_CD_DESC        VARCHAR2(100)
);

--------------------------------------------------------
--  DDL for Table DUTY_STATION
--------------------------------------------------------
CREATE TABLE HHS_HR.DUTY_STATION
(
	STATE_OR_COUNTRY_NAME        VARCHAR2(30),
	GEO_CODE                     VARCHAR2(12),
	STATE_ABBRV                  VARCHAR2(2),
	CITY_OR_COUNTRY_NAME         VARCHAR2(50),
	COUNTY                       VARCHAR2(50),
	STATE_OR_COUNTRY_CD          VARCHAR2(2)
);

--------------------------------------------------------
--  DDL for Table LEGAL_AUTHORITY
--------------------------------------------------------
CREATE TABLE HHS_HR.LEGAL_AUTHORITY
(
	AUTH_CODE            VARCHAR2(20),
	AUTH_DESC            VARCHAR2(100),
	STATUS               VARCHAR2(25),
	EFFECTIVE_DATE       DATE,
	AS_OF_DATE           DATE
) ;

--------------------------------------------------------
--  DDL for Table NATURE_OF_ACTION
--------------------------------------------------------
CREATE TABLE HHS_HR.NATURE_OF_ACTION
(
	NOA_CODE             VARCHAR2(20),
	NOA_DESC             VARCHAR2(100),
	NOA_SUFFIX_CD        VARCHAR2(1),
	LOAD_DATE            DATE
);

--------------------------------------------------------
--  DDL for Table PAY_PLAN
--------------------------------------------------------
CREATE TABLE HHS_HR.PAY_PLAN
(
	POSITION_PAY_PLAN        VARCHAR2(2),
	PAY_PLAN_DESC            VARCHAR2(100)
);


--------------------------------------------------------
--  DDL for Table OCCUPATIONAL_SERIES
--------------------------------------------------------
CREATE TABLE HHS_HR.OCCUPATIONAL_SERIES
(
	POSITION_SERIES        VARCHAR2(8),
	SERIES_DESC            VARCHAR2(100)
);

--------------------------------------------------------
--  DDL for Table PS_DEPT_TBL
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PS_DEPT_TBL" 
(
	"SETID" 					VARCHAR2(5) NOT NULL ENABLE, 
	"DEPTID" 						VARCHAR2(10) NOT NULL ENABLE, 
	"EFFDT" 						DATE NOT NULL ENABLE, 
	"EFF_STATUS" 					VARCHAR2(1) NOT NULL ENABLE, 
	"DESCR" 						VARCHAR2(30) NOT NULL ENABLE, 
	"DESCRSHORT" 					VARCHAR2(10) NOT NULL ENABLE, 
	"COMPANY" 						VARCHAR2(3) NOT NULL ENABLE, 
	"SETID_LOCATION" 				VARCHAR2(5) NOT NULL ENABLE, 
	"LOCATION" 						VARCHAR2(10) NOT NULL ENABLE, 
	"TAX_LOCATION_CD" 				VARCHAR2(10) NOT NULL ENABLE, 
	"MANAGER_ID" 					VARCHAR2(11) NOT NULL ENABLE, 
	"MANAGER_POSN" 					VARCHAR2(8) NOT NULL ENABLE, 
	"BUDGET_YR_END_DT" 				NUMBER(*,0) NOT NULL ENABLE, 
	"BUDGET_LVL" 					VARCHAR2(1) NOT NULL ENABLE, 
	"GL_EXPENSE" 					VARCHAR2(35) NOT NULL ENABLE, 
	"EEO4_FUNCTION" 				VARCHAR2(2) NOT NULL ENABLE, 
	"CAN_IND_SECTOR" 				VARCHAR2(3) NOT NULL ENABLE, 
	"ACCIDENT_INS" 					VARCHAR2(3) NOT NULL ENABLE, 
	"SI_ACCIDENT_NUM" 				VARCHAR2(15) NOT NULL ENABLE, 
	"HAZARD" 						VARCHAR2(4) NOT NULL ENABLE, 
	"ESTABID" 						VARCHAR2(12) NOT NULL ENABLE, 
	"RISKCD" 						VARCHAR2(6) NOT NULL ENABLE, 
	"GRADE" 						VARCHAR2(3) NOT NULL ENABLE, 
	"GVT_DESCR40" 					VARCHAR2(40) NOT NULL ENABLE, 
	"GVT_SUB_AGENCY" 				VARCHAR2(2) NOT NULL ENABLE, 
	"GVT_PAR_LINE2" 				VARCHAR2(10) NOT NULL ENABLE, 
	"GVT_PAR_LINE3" 				VARCHAR2(10) NOT NULL ENABLE, 
	"GVT_PAR_LINE4" 				VARCHAR2(10) NOT NULL ENABLE, 
	"GVT_PAR_LINE5" 				VARCHAR2(10) NOT NULL ENABLE, 
	"GVT_PAR_DESCR2" 				VARCHAR2(40) NOT NULL ENABLE, 
	"GVT_PAR_DESCR3" 				VARCHAR2(40) NOT NULL ENABLE, 
	"GVT_PAR_DESCR4" 				VARCHAR2(40) NOT NULL ENABLE, 
	"GVT_PAR_DESCR5" 				VARCHAR2(40) NOT NULL ENABLE, 
	"FTE_EDIT_INDC" 				VARCHAR2(1) NOT NULL ENABLE, 
	"DEPT_TENURE_FLG" 				VARCHAR2(1) NOT NULL ENABLE, 
	"TL_DISTRIB_INFO" 				VARCHAR2(1) NOT NULL ENABLE, 
	"USE_BUDGETS" 					VARCHAR2(1) NOT NULL ENABLE, 
	"USE_ENCUMBRANCES" 				VARCHAR2(1) NOT NULL ENABLE, 
	"USE_DISTRIBUTION" 				VARCHAR2(1) NOT NULL ENABLE, 
	"BUDGET_DEPTID" 				VARCHAR2(10) NOT NULL ENABLE, 
	"HP_STATS_DEPT_CD" 				VARCHAR2(3) NOT NULL ENABLE, 
	"HP_STATS_FACULTY" 				VARCHAR2(5) NOT NULL ENABLE, 
	"MANAGER_NAME" 					VARCHAR2(30) NOT NULL ENABLE, 
	"ACCOUNTING_OWNER" 				VARCHAR2(30) NOT NULL ENABLE, 
	"COUNTRY_GRP" 					VARCHAR2(18) NOT NULL ENABLE, 
	"CLASS_UNIT_NZL" 				VARCHAR2(5) NOT NULL ENABLE, 
	"ORG_UNIT_AUS" 					VARCHAR2(4) NOT NULL ENABLE, 
	"WORK_SECTOR_AUS" 				VARCHAR2(1) NOT NULL ENABLE, 
	"APS_AGENT_CD_AUS" 				NUMBER(*,0) NOT NULL ENABLE, 
	"IND_COMMITTEE_BEL" 			VARCHAR2(3) NOT NULL ENABLE, 
	"NACE_CD_BEL" 					VARCHAR2(10) NOT NULL ENABLE
);

--------------------------------------------------------
--  DDL for Table PS_HE_EWIT_DEPT_1
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PS_HE_EWIT_DEPT_1" 
(
	"SETID" 				VARCHAR2(5) NOT NULL ENABLE, 
	"DEPTID" 				VARCHAR2(10) NOT NULL ENABLE, 
	"DESCR" 				VARCHAR2(30) NOT NULL ENABLE, 
	"GVT_PAR_LINE2" 		VARCHAR2(10) NOT NULL ENABLE, 
	"GVT_PAR_DESCR2" 		VARCHAR2(40) NOT NULL ENABLE, 
	"GVT_PAR_LINE3" 		VARCHAR2(10) NOT NULL ENABLE, 
	"GVT_PAR_DESCR3" 		VARCHAR2(40) NOT NULL ENABLE, 
	"GVT_PAR_LINE4" 		VARCHAR2(10) NOT NULL ENABLE, 
	"GVT_PAR_DESCR4" 		VARCHAR2(40) NOT NULL ENABLE, 
	"GVT_PAR_LINE5" 		VARCHAR2(10) NOT NULL ENABLE, 
	"GVT_PAR_DESCR5" 		VARCHAR2(40) NOT NULL ENABLE
);

--------------------------------------------------------
--  DDL for Table PS_HE_RECRUIT_EWIT
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PS_HE_RECRUIT_EWIT"
(
	"HRS_JOB_OPENING_ID" 			NUMBER(15,0) NOT NULL ENABLE, 
	"HE_COMP_ALLOWANCE" 			VARCHAR2(1) NOT NULL ENABLE, 
	"HE_DENTIST_PAY" 				VARCHAR2(1) NOT NULL ENABLE, 
	"HE_NON_STANDARD_PA" 			VARCHAR2(1) NOT NULL ENABLE, 
	"HE_POSITION_DESCR" 			VARCHAR2(1) NOT NULL ENABLE, 
	"HE_RECRUIT_INCENT" 			VARCHAR2(1) NOT NULL ENABLE, 
	"HE_RELOCATIONBONUS" 			VARCHAR2(1) NOT NULL ENABLE, 
	"ACCT_CD" 						VARCHAR2(25) NOT NULL ENABLE
);

--------------------------------------------------------
--  DDL for Table PS_HRS_JO_LOC
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PS_HRS_JO_LOC" 
(
	"HRS_JOB_OPENING_ID" 			NUMBER(15,0) NOT NULL ENABLE, 
	"LOCATION"						VARCHAR2(10) NOT NULL ENABLE, 
	"OPENINGS_TARGET" 				NUMBER(*,0) NOT NULL ENABLE, 
	"HRS_JO_PRM_LOC_FLG" 			VARCHAR2(1) NOT NULL ENABLE, 
	"HRS_ROW_ADD_DTTM" 				TIMESTAMP (6), 
	"HRS_ROW_ADD_OPRID" 			VARCHAR2(30) NOT NULL ENABLE, 
	"HRS_ROW_UPD_DTTM" 				TIMESTAMP (6), 
	"HRS_ROW_UPD_OPRID" 			VARCHAR2(30) NOT NULL ENABLE
);

--------------------------------------------------------
--  DDL for Table PS_HRS_JO_NAME
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PS_HRS_JO_NAME" 
(
	"HRS_JOB_OPENING_ID" 		NUMBER(15,0) NOT NULL ENABLE, 
	"SEQUENCE_NBR" 				NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" 						VARCHAR2(50) NOT NULL ENABLE, 
	"HRS_ROW_ADD_DTTM" 			TIMESTAMP (6), 
	"HRS_ROW_ADD_OPRID" 		VARCHAR2(30) NOT NULL ENABLE, 
	"HRS_ROW_UPD_DTTM" 			TIMESTAMP (6), 
	"HRS_ROW_UPD_OPRID" 		VARCHAR2(30) NOT NULL ENABLE
);

--------------------------------------------------------
--  DDL for Table PS_HRS_JO_POSN
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PS_HRS_JO_POSN" 
(
	"HRS_JOB_OPENING_ID" 		NUMBER(15,0) NOT NULL ENABLE, 
	"POSITION_NBR" 				VARCHAR2(8) NOT NULL ENABLE, 
	"HRS_JO_PRM_PSN_FLG" 		VARCHAR2(1) NOT NULL ENABLE, 
	"HRS_ROW_ADD_DTTM" 			TIMESTAMP (6), 
	"HRS_ROW_ADD_OPRID" 		VARCHAR2(30) NOT NULL ENABLE, 
	"HRS_ROW_UPD_DTTM" 			TIMESTAMP (6), 
	"HRS_ROW_UPD_OPRID" 		VARCHAR2(30) NOT NULL ENABLE
);

--------------------------------------------------------
--  DDL for Table PS_HRS_JO_RPL
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PS_HRS_JO_RPL" 
(
	"HRS_JOB_OPENING_ID" 		NUMBER(15,0) NOT NULL ENABLE, 
	"EMPLID" 					VARCHAR2(11) NOT NULL ENABLE, 
	"HE_VACATED_DT" 			DATE, 
	"HRS_ROW_ADD_DTTM" 			TIMESTAMP (6), 
	"HRS_ROW_ADD_OPRID" 		VARCHAR2(30) NOT NULL ENABLE, 
	"HRS_ROW_UPD_DTTM" 			TIMESTAMP (6), 
	"HRS_ROW_UPD_OPRID" 		VARCHAR2(30) NOT NULL ENABLE
);

--------------------------------------------------------
--  DDL for Table PS_HRS_JO_RQMT
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PS_HRS_JO_RQMT" 
(
	"HRS_JOB_OPENING_ID" 				NUMBER(15,0) NOT NULL ENABLE, 
	"HRS_JO_RQMT_SEQ" 					NUMBER(*,0) NOT NULL ENABLE, 
	"JOBCODE" 							VARCHAR2(6) NOT NULL ENABLE, 
	"HRS_JO_PRM_JCD_FLG" 				VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_NUM_APPS_CONS" 				NUMBER(*,0) NOT NULL ENABLE, 
	"GVT_RQSN_CERT_NBR" 				VARCHAR2(10) NOT NULL ENABLE, 
	"GVT_RQSN_CERT_SRC" 				VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_RQSN_CERT_STS" 				VARCHAR2(1) NOT NULL ENABLE, 
	"DT_DUE" 							DATE, 
	"DT_ISSUED" 						DATE, 
	"DT_RECVD" 							DATE, 
	"DT_REQUESTED" 						DATE, 
	"DT_RETURNED" 						DATE, 
	"GVT_DT_EXTENDED" 					DATE, 
	"GVT_DT_RET_FRM_SO" 				DATE, 
	"GVT_DT_SENT_TO_SO" 				DATE, 
	"REG_REGION" 						VARCHAR2(5) NOT NULL ENABLE, 
	"FULL_PART_TIME" 					VARCHAR2(1) NOT NULL ENABLE, 
	"REG_TEMP"							VARCHAR2(1) NOT NULL ENABLE, 
	"BEGIN_DT"							DATE, 
	"END_DT" 							DATE, 
	"STD_HOURS" 						NUMBER(6,2) NOT NULL ENABLE, 
	"STD_HRS_FREQUENCY" 				VARCHAR2(5) NOT NULL ENABLE, 
	"SHIFT" 							VARCHAR2(1) NOT NULL ENABLE, 
	"HRS_JO_MIN_RT" 					NUMBER(21,6) NOT NULL ENABLE, 
	"HRS_JO_MAX_RT" 					NUMBER(21,6) NOT NULL ENABLE, 
	"PAY_FREQ_ABBRV" 					VARCHAR2(1) NOT NULL ENABLE, 
	"CURRENCY_CD" 						VARCHAR2(3) NOT NULL ENABLE, 
	"SAL_ADMIN_PLAN"					VARCHAR2(4) NOT NULL ENABLE, 
	"GRADE_FROM" 						VARCHAR2(3) NOT NULL ENABLE, 
	"GRADE_TO" 							VARCHAR2(3) NOT NULL ENABLE, 
	"STEP_FROM" 						NUMBER(*,0) NOT NULL ENABLE, 
	"STEP_TO" 							NUMBER(*,0) NOT NULL ENABLE, 
	"HRS_TRAVEL_PERCENT" 				VARCHAR2(1) NOT NULL ENABLE, 
	"MANAGER_LEVEL" 					VARCHAR2(2) NOT NULL ENABLE, 
	"FLSA_STATUS" 						VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_SUMMER_APPT" 					VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_NTE_DATE" 						DATE, 
	"GVT_NTE_DAYS" 						NUMBER(*,0) NOT NULL ENABLE, 
	"GVT_LEO_POSITION" 					VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_POSN_SENS_CD" 					VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_TYPE_OF_APPT" 					VARCHAR2(2) NOT NULL ENABLE, 
	"HRS_ROW_ADD_DTTM" 					TIMESTAMP (6), 
	"HRS_ROW_ADD_OPRID" 				VARCHAR2(30) NOT NULL ENABLE, 
	"HRS_ROW_UPD_DTTM" 					TIMESTAMP (6), 
	"HRS_ROW_UPD_OPRID" 				VARCHAR2(30) NOT NULL ENABLE
);

--------------------------------------------------------
--  DDL for Table PS_HRS_JOB_OPENING
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PS_HRS_JOB_OPENING" 
(
	"HRS_JOB_OPENING_ID" 				NUMBER(15,0) NOT NULL ENABLE, 
	"HRS_RCRT_TMPL_ID" 					NUMBER(15,0) NOT NULL ENABLE, 
	"HRS_JO_TYPE" 						VARCHAR2(1) NOT NULL ENABLE, 
	"REFERRAL_PGM_ID" 					VARCHAR2(12) NOT NULL ENABLE, 
	"ORIGINATOR_ID" 					VARCHAR2(11) NOT NULL ENABLE, 
	"MANAGER_ID" 						VARCHAR2(11) NOT NULL ENABLE, 
	"RECRUITER_ID" 						VARCHAR2(11) NOT NULL ENABLE, 
	"GVT_SEL_OFFICIAL" 					VARCHAR2(11) NOT NULL ENABLE, 
	"OPEN_DT" 							DATE, 
	"CLOSE_DT" 							DATE, 
	"STATUS_CODE" 						VARCHAR2(3) NOT NULL ENABLE, 
	"STATUS_REASON" 					VARCHAR2(3) NOT NULL ENABLE, 
	"STATUS_DT" 						DATE NOT NULL ENABLE, 
	"HRS_OPENING_LIMIT" 				VARCHAR2(1) NOT NULL ENABLE, 
	"OPENINGS_CNT" 						NUMBER(*,0) NOT NULL ENABLE, 
	"OPENINGS_TARGET" 					NUMBER(*,0) NOT NULL ENABLE, 
	"HOT_JOB" 							VARCHAR2(1) NOT NULL ENABLE, 
	"BUSINESS_UNIT" 					VARCHAR2(5) NOT NULL ENABLE, 
	"SETID_DEPT" 						VARCHAR2(5) NOT NULL ENABLE, 
	"DEPTID" 							VARCHAR2(10) NOT NULL ENABLE, 
	"COMPANY" 							VARCHAR2(3) NOT NULL ENABLE, 
	"HRS_PRM_JOBCODE" 					VARCHAR2(6) NOT NULL ENABLE, 
	"HRS_PRM_POSITION" 					VARCHAR2(8) NOT NULL ENABLE, 
	"HRS_PRM_LOCATION" 					VARCHAR2(10) NOT NULL ENABLE, 
	"HRS_PRM_LOC_AREA" 					NUMBER(15,0) NOT NULL ENABLE, 
	"HRS_PRM_PST_TITLE" 				VARCHAR2(200) NOT NULL ENABLE, 
	"DESIRED_START_DT" 					DATE, 
	"WC_COUNCIL_ID" 					VARCHAR2(9) NOT NULL ENABLE, 
	"ENCUMB_DT_INDC" 					VARCHAR2(1) NOT NULL ENABLE, 
	"PROJECTED_FILL_DT" 				DATE, 
	"AUTHORIZATION_DT"					DATE, 
	"ESTABID" 							VARCHAR2(12) NOT NULL ENABLE, 
	"COUNTRY" 							VARCHAR2(3) NOT NULL ENABLE, 
	"CITIZENSHIP_STATUS" 				VARCHAR2(1) NOT NULL ENABLE, 
	"MIN_AGE" 							NUMBER(*,0) NOT NULL ENABLE, 
	"MAX_AGE" 							NUMBER(*,0) NOT NULL ENABLE, 
	"SEX" 								VARCHAR2(1) NOT NULL ENABLE, 
	"HRS_CONTACT_ID" 					NUMBER(15,0) NOT NULL ENABLE, 
	"GVT_STAFF_SPCLST" 					VARCHAR2(11) NOT NULL ENABLE, 
	"GVT_CONSIDER_AREA" 				VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_DRAFT_STATUS" 					VARCHAR2(1) NOT NULL ENABLE, 
	"HRS_G_JO_TYPE" 					VARCHAR2(1) NOT NULL ENABLE, 
	"JOB_FAMILY" 						VARCHAR2(6) NOT NULL ENABLE, 
	"HRS_ROW_ADD_DTTM" 					TIMESTAMP (6), 
	"HRS_ROW_ADD_OPRID" 				VARCHAR2(30) NOT NULL ENABLE, 
	"HRS_ROW_UPD_DTTM" 					TIMESTAMP (6), 
	"HRS_ROW_UPD_OPRID" 				VARCHAR2(30) NOT NULL ENABLE, 
	"GVT_RECR_OFFICE" 					VARCHAR2(10) NOT NULL ENABLE, 
	"HE_APPROVALO_OPRID" 				VARCHAR2(30) NOT NULL ENABLE, 
	"HE_COMMENTS" 						LONG
);

--------------------------------------------------------
--  DDL for Table PS_HRS_LOCATION_I
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PS_HRS_LOCATION_I" 
(
	"SETID" 				VARCHAR2(5), 
	"LOCATION" 				VARCHAR2(10), 
	"EFFDT" 				DATE, 
	"COUNTRY" 				VARCHAR2(3), 
	"STATE" 				VARCHAR2(6), 
	"DESCR" 				VARCHAR2(30), 
	"DESCRSHORT" 			VARCHAR2(10)
);

--------------------------------------------------------
--  DDL for Table PS_JOBCODE_TBL
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PS_JOBCODE_TBL" 
(
	"SETID" 					VARCHAR2(5) NOT NULL ENABLE, 
	"JOBCODE" 					VARCHAR2(6) NOT NULL ENABLE, 
	"EFFDT" 					DATE NOT NULL ENABLE, 
	"EFF_STATUS" 				VARCHAR2(1) NOT NULL ENABLE, 
	"DESCR" 					VARCHAR2(30) NOT NULL ENABLE, 
	"DESCRSHORT" 				VARCHAR2(10) NOT NULL ENABLE, 
	"JOB_FUNCTION" 				VARCHAR2(3) NOT NULL ENABLE, 
	"SETID_SALARY" 				VARCHAR2(5) NOT NULL ENABLE, 
	"SAL_ADMIN_PLAN" 			VARCHAR2(4) NOT NULL ENABLE, 
	"GRADE" 					VARCHAR2(3) NOT NULL ENABLE, 
	"STEP" 						NUMBER(*,0) NOT NULL ENABLE, 
	"MANAGER_LEVEL" 			VARCHAR2(2) NOT NULL ENABLE, 
	"SURVEY_SALARY" 			NUMBER(*,0) NOT NULL ENABLE, 
	"SURVEY_JOB_CODE" 			VARCHAR2(8) NOT NULL ENABLE, 
	"UNION_CD" 					VARCHAR2(3) NOT NULL ENABLE, 
	"RETRO_RATE" 				NUMBER(6,4) NOT NULL ENABLE, 
	"RETRO_PERCENT" 			NUMBER(6,4) NOT NULL ENABLE, 
	"CURRENCY_CD" 				VARCHAR2(3) NOT NULL ENABLE, 
	"STD_HOURS" 				NUMBER(6,2) NOT NULL ENABLE, 
	"STD_HRS_FREQUENCY" 		VARCHAR2(5) NOT NULL ENABLE, 
	"COMP_FREQUENCY" 			VARCHAR2(5) NOT NULL ENABLE, 
	"WORKERS_COMP_CD" 			VARCHAR2(4) NOT NULL ENABLE, 
	"JOB_FAMILY" 				VARCHAR2(6) NOT NULL ENABLE, 
	"JOB_KNOWHOW_POINTS" 		NUMBER(*,0) NOT NULL ENABLE, 
	"JOB_ACCNTAB_POINTS" 		NUMBER(*,0) NOT NULL ENABLE, 
	"JOB_PROBSLV_POINTS" 		NUMBER(*,0) NOT NULL ENABLE, 
	"JOB_POINTS_TOTAL" 			NUMBER(*,0) NOT NULL ENABLE, 
	"JOB_KNOWHOW_PCT" 			NUMBER(4,1) NOT NULL ENABLE, 
	"JOB_ACCNTAB_PCT" 			NUMBER(4,1) NOT NULL ENABLE, 
	"JOB_PROBSLV_PCT" 			NUMBER(4,1) NOT NULL ENABLE, 
	"REG_TEMP" 					VARCHAR2(1) NOT NULL ENABLE, 
	"DIRECTLY_TIPPED" 			VARCHAR2(1) NOT NULL ENABLE, 
	"MED_CHKUP_REQ" 			VARCHAR2(1) NOT NULL ENABLE, 
	"FLSA_STATUS" 				VARCHAR2(1) NOT NULL ENABLE, 
	"EEO1CODE" 					VARCHAR2(1) NOT NULL ENABLE, 
	"EEO4CODE" 					VARCHAR2(1) NOT NULL ENABLE, 
	"EEO5CODE" 					VARCHAR2(2) NOT NULL ENABLE, 
	"EEO6CODE" 					VARCHAR2(1) NOT NULL ENABLE, 
	"EEO_JOB_GROUP" 			VARCHAR2(4) NOT NULL ENABLE, 
	"US_SOC_CD" 				VARCHAR2(10) NOT NULL ENABLE, 
	"IPEDSSCODE" 				VARCHAR2(1) NOT NULL ENABLE, 
	"US_OCC_CD" 				VARCHAR2(3) NOT NULL ENABLE, 
	"CAN_PAYEQ_JOB_CLS" 		VARCHAR2(3) NOT NULL ENABLE, 
	"CAN_NOC_CD" 				VARCHAR2(4) NOT NULL ENABLE, 
	"SEASONAL" 					VARCHAR2(1) NOT NULL ENABLE, 
	"BPS_ACTIVITY_CD"			VARCHAR2(6) NOT NULL ENABLE, 
	"FUNCTION_CD" 				VARCHAR2(2) NOT NULL ENABLE, 
	"BA_CD" 					VARCHAR2(3) NOT NULL ENABLE, 
	"TECHNICAL" 				VARCHAR2(1) NOT NULL ENABLE, 
	"MED_SURV_REQ" 				VARCHAR2(1) NOT NULL ENABLE, 
	"EMP_CATEGRY_FRA" 			VARCHAR2(3) NOT NULL ENABLE, 
	"ACTIVITY_TYPE_FRA" 		VARCHAR2(3) NOT NULL ENABLE, 
	"INSEE_CD_FRA" 				VARCHAR2(4) NOT NULL ENABLE, 
	"JOB_CTG_FRA_CD" 			VARCHAR2(2) NOT NULL ENABLE, 
	"UK_SOC_CD" 				VARCHAR2(2) NOT NULL ENABLE, 
	"GVT_PAY_PLAN" 				VARCHAR2(2) NOT NULL ENABLE, 
	"GVT_OCC_SERIES" 			VARCHAR2(4) NOT NULL ENABLE, 
	"TRN_PROGRAM" 				VARCHAR2(6) NOT NULL ENABLE, 
	"COMPANY" 					VARCHAR2(3) NOT NULL ENABLE, 
	"GVT_FUNC_CLASS" 			VARCHAR2(2) NOT NULL ENABLE, 
	"GVT_POSN_TITLE_CD" 		VARCHAR2(4) NOT NULL ENABLE, 
	"GVT_OFFICIAL_DESCR" 		VARCHAR2(70) NOT NULL ENABLE, 
	"GVT_ORG_TTL_CD" 			VARCHAR2(4) NOT NULL ENABLE, 
	"GVT_ORG_TTL_DESCR" 		VARCHAR2(70) NOT NULL ENABLE, 
	"GVT_PAY_BASIS" 			VARCHAR2(2) NOT NULL ENABLE, 
	"GVT_SUB_AGENCY" 			VARCHAR2(2) NOT NULL ENABLE, 
	"GVT_POI" 					VARCHAR2(4) NOT NULL ENABLE, 
	"GVT_PAREN_TITLE" 			VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_OPM_CERT_NBR" 			VARCHAR2(8) NOT NULL ENABLE, 
	"GVT_POSN_CLASS_STD" 		VARCHAR2(254) NOT NULL ENABLE, 
	"GVT_POSN_SENS_CD" 			VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_IA_ACTIONS" 			VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_EXEC_FIN_DISCL" 		VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_EMP_FIN_INT" 			VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_PATCOB_CD" 			VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_CLS_STANDARD" 			VARCHAR2(15) NOT NULL ENABLE, 
	"GVT_CLASSIFIER_ID" 		VARCHAR2(11) NOT NULL ENABLE, 
	"GVT_DT_CLASSIFIED" 		DATE, 
	"BARG_UNIT" 				VARCHAR2(4) NOT NULL ENABLE, 
	"GVT_FUND_SOURCE" 			VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_LEO_POSITION" 			VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_PERF_PLAN" 			VARCHAR2(8) NOT NULL ENABLE, 
	"GVT_TARGET_GRADE" 			VARCHAR2(2) NOT NULL ENABLE, 
	"GVT_PI_UPD_IND" 			VARCHAR2(1) NOT NULL ENABLE, 
	"ENCUMBER_INDC" 			VARCHAR2(1) NOT NULL ENABLE, 
	"POSN_MGMT_INDC" 			VARCHAR2(1) NOT NULL ENABLE, 
	"EG_ACADEMIC_RANK" 			VARCHAR2(3) NOT NULL ENABLE, 
	"EG_GROUP" 					VARCHAR2(6) NOT NULL ENABLE, 
	"HP_STATS_DUTIES" 			VARCHAR2(2) NOT NULL ENABLE, 
	"HP_STATS_RPT_FLAG" 		VARCHAR2(1) NOT NULL ENABLE, 
	"ENCUMB_SAL_OPTN" 			VARCHAR2(3) NOT NULL ENABLE, 
	"ENCUMB_SAL_AMT" 			NUMBER(18,3) NOT NULL ENABLE, 
	"INAIL_CODE" 				VARCHAR2(11) NOT NULL ENABLE, 
	"ASCO_CD_AUS" 				VARCHAR2(6) NOT NULL ENABLE, 
	"PKG_TEMPLATE_ID" 			VARCHAR2(10) NOT NULL ENABLE, 
	"PKG_RULE_ID" 				VARCHAR2(10) NOT NULL ENABLE, 
	"FUNCTION_AUS" 				VARCHAR2(1) NOT NULL ENABLE, 
	"ANN_CNTACT_HRS_AUS" 		NUMBER(6,2) NOT NULL ENABLE, 
	"TEACH_WEEKS_AUS" 			NUMBER(*,0) NOT NULL ENABLE, 
	"CASUAL_TYPE_AUS" 			VARCHAR2(1) NOT NULL ENABLE, 
	"WORK_DAY_HOURS" 			NUMBER(6,2) NOT NULL ENABLE, 
	"FA_PAY_PROGRAM" 			VARCHAR2(3) NOT NULL ENABLE, 
	"ELECTION_GROUP" 			VARCHAR2(5) NOT NULL ENABLE, 
	"LABOR_AGREEMENT" 			VARCHAR2(6) NOT NULL ENABLE, 
	"FP_PROF_CATG" 				VARCHAR2(3) NOT NULL ENABLE, 
	"FP_JOB_FMLY" 				VARCHAR2(4) NOT NULL ENABLE, 
	"FP_OFF_COLAG" 				VARCHAR2(1) NOT NULL ENABLE, 
	"FP_MATRIX_TYP" 			VARCHAR2(3) NOT NULL ENABLE, 
	"FP_MATRIX_CD" 				VARCHAR2(4) NOT NULL ENABLE, 
	"FP_BUSINESS_CD" 			VARCHAR2(4) NOT NULL ENABLE, 
	"FP_JOBCD_ACC" 				VARCHAR2(1) NOT NULL ENABLE, 
	"FP_ATCH_AREA" 				VARCHAR2(4) NOT NULL ENABLE, 
	"FP_JOB_TYP" 				VARCHAR2(2) NOT NULL ENABLE, 
	"FP_AUTO_RATFY" 			VARCHAR2(1) NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" 			DATE, 
	"REG_REGION" 				VARCHAR2(5) NOT NULL ENABLE, 
	"SAL_RANGE_MIN_RATE" 		NUMBER(18,6) NOT NULL ENABLE, 
	"SAL_RANGE_MID_RATE" 		NUMBER(18,6) NOT NULL ENABLE, 
	"SAL_RANGE_MAX_RATE" 		NUMBER(18,6) NOT NULL ENABLE, 
	"SAL_RANGE_CURRENCY" 		VARCHAR2(3) NOT NULL ENABLE, 
	"SAL_RANGE_FREQ" 			VARCHAR2(5) NOT NULL ENABLE, 
	"JOB_PROFILE_ID" 			VARCHAR2(8) NOT NULL ENABLE, 
	"DESCRLONG" 				LONG
);

CREATE INDEX HHS_HR.PS_JOBCODE_TBL_IDX1 ON HHS_HR.PS_JOBCODE_TBL (SETID ASC, JOBCODE ASC, EFFDT ASC);

CREATE INDEX HHS_HR.PS_JOBCODE_TBL_IDX2 ON HHS_HR.PS_JOBCODE_TBL (EFF_STATUS ASC);

--------------------------------------------------------
--  DDL for Table PS_PERSONAL_DATA_VW
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PS_PERSONAL_DATA_VW" 
(
	"EMPLID" 					VARCHAR2(11), 
	"COUNTRY_NM_FORMAT" 		VARCHAR2(3), 
	"NAME" 						VARCHAR2(50), 
	"NAME_INITIALS" 			VARCHAR2(6), 
	"NAME_PREFIX" 				VARCHAR2(4), 
	"NAME_SUFFIX" 				VARCHAR2(15), 
	"NAME_ROYAL_PREFIX" 		VARCHAR2(15), 
	"NAME_ROYAL_SUFFIX" 		VARCHAR2(15), 
	"NAME_TITLE" 				VARCHAR2(30), 
	"LAST_NAME_SRCH" 			VARCHAR2(30), 
	"FIRST_NAME_SRCH" 			VARCHAR2(30), 
	"LAST_NAME" 				VARCHAR2(30), 
	"FIRST_NAME" 				VARCHAR2(30), 
	"MIDDLE_NAME" 				VARCHAR2(30), 
	"SECOND_LAST_NAME" 			VARCHAR2(30), 
	"SECOND_LAST_SRCH" 			VARCHAR2(30), 
	"NAME_AC" 					VARCHAR2(50), 
	"PREF_FIRST_NAME" 			VARCHAR2(30), 
	"PARTNER_LAST_NAME" 		VARCHAR2(30), 
	"PARTNER_ROY_PREFIX" 		VARCHAR2(15), 
	"LAST_NAME_PREF_NLD" 		VARCHAR2(1), 
	"NAME_DISPLAY" 				VARCHAR2(50), 
	"NAME_FORMAL" 				VARCHAR2(60), 
	"CAMPUS_ID" 				VARCHAR2(16), 
	"COUNTRY" 					VARCHAR2(3), 
	"ADDRESS1" 					VARCHAR2(55), 
	"ADDRESS2" 					VARCHAR2(55), 
	"ADDRESS3" 					VARCHAR2(55), 
	"ADDRESS4" 					VARCHAR2(55), 
	"CITY" 						VARCHAR2(30), 
	"NUM1" 						VARCHAR2(6), 
	"NUM2" 						VARCHAR2(6), 
	"HOUSE_TYPE" 				VARCHAR2(2), 
	"ADDR_FIELD1" 				VARCHAR2(2), 
	"ADDR_FIELD2" 				VARCHAR2(4), 
	"ADDR_FIELD3" 				VARCHAR2(4), 
	"COUNTY" 					VARCHAR2(30), 
	"STATE" 					VARCHAR2(6), 
	"POSTAL" 					VARCHAR2(12), 
	"GEO_CODE" 					VARCHAR2(11), 
	"IN_CITY_LIMIT" 			VARCHAR2(1), 
	"COUNTRY_OTHER" 			VARCHAR2(3), 
	"ADDRESS1_OTHER"			VARCHAR2(55), 
	"ADDRESS2_OTHER" 			VARCHAR2(55), 
	"ADDRESS3_OTHER" 			VARCHAR2(55), 
	"ADDRESS4_OTHER" 			VARCHAR2(55), 
	"CITY_OTHER" 				VARCHAR2(30), 
	"COUNTY_OTHER" 				VARCHAR2(30), 
	"STATE_OTHER" 				VARCHAR2(6), 
	"POSTAL_OTHER" 				VARCHAR2(12), 
	"NUM1_OTHER" 				VARCHAR2(6), 
	"NUM2_OTHER" 				VARCHAR2(6), 
	"HOUSE_TYPE_OTHER" 			VARCHAR2(2), 
	"ADDR_FIELD1_OTHER" 		VARCHAR2(2), 
	"ADDR_FIELD2_OTHER" 		VARCHAR2(4), 
	"ADDR_FIELD3_OTHER" 		VARCHAR2(4), 
	"IN_CITY_LMT_OTHER" 		VARCHAR2(1), 
	"GEO_CODE_OTHER" 			VARCHAR2(11), 
	"COUNTRY_CODE" 				VARCHAR2(3), 
	"PHONE" 					VARCHAR2(24), 
	"EXTENSION" 				VARCHAR2(6), 
	"VA_BENEFIT" 				VARCHAR2(1), 
	"DEATH_CERTIF_NBR" 			VARCHAR2(10), 
	"FERPA" 					VARCHAR2(1), 
	"PLACE_OF_DEATH" 			VARCHAR2(30), 
	"US_WORK_ELIGIBILTY" 		VARCHAR2(1), 
	"MILITARY_STATUS" 			VARCHAR2(1), 
	"CITIZEN_PROOF1" 			VARCHAR2(10), 
	"CITIZEN_PROOF2" 			VARCHAR2(10), 
	"MEDICARE_ENTLD_DT" 		DATE, 
	"HONSEKI_JPN" 				VARCHAR2(2), 
	"MILITARY_STAT_ITA" 		VARCHAR2(1), 
	"MILITARY_TYPE_ITA" 		VARCHAR2(2), 
	"MILITARY_RANK_ITA" 		VARCHAR2(50), 
	"MILITARY_END_ITA" 			DATE, 
	"ENTRY_DT_FRA" 				DATE, 
	"MILIT_SITUATN_FRA" 		VARCHAR2(3), 
	"CPAMID" 					VARCHAR2(6), 
	"BILINGUALISM_CODE" 		VARCHAR2(1), 
	"HEALTH_CARE_NBR" 			VARCHAR2(12), 
	"HEALTH_CARE_STATE" 		VARCHAR2(6), 
	"MILIT_SITUATN_ESP" 		VARCHAR2(3), 
	"SOC_SEC_AFF_DT" 			DATE, 
	"MILITARY_STAT_GER" 		VARCHAR2(1), 
	"EXPCTD_MILITARY_DT" 		DATE, 
	"HR_RESPONSIBLE_ID" 		VARCHAR2(11), 
	"SMOKER" 					VARCHAR2(1), 
	"SMOKER_DT" 				DATE, 
	"GVT_CRED_MIL_SVCE" 		VARCHAR2(4), 
	"GVT_MILITARY_COMP" 		VARCHAR2(1), 
	"GVT_MIL_GRADE" 			VARCHAR2(3), 
	"GVT_MIL_RESRVE_CAT" 		VARCHAR2(1), 
	"GVT_MIL_SEP_RET" 			VARCHAR2(1), 
	"GVT_MIL_SVCE_END" 			DATE, 
	"GVT_MIL_SVCE_START" 		DATE, 
	"GVT_MIL_VERIFY" 			VARCHAR2(1), 
	"GVT_PAR_NBR_LAST" 			NUMBER(38,0), 
	"GVT_UNIF_SVC_CTR" 			VARCHAR2(1), 
	"GVT_VET_PREF_APPT" 		VARCHAR2(1), 
	"GVT_VET_PREF_RIF" 			VARCHAR2(1), 
	"GVT_CHANGE_FLAG" 			VARCHAR2(1), 
	"GVT_DRAFT_STATUS" 			VARCHAR2(1), 
	"GVT_YR_ATTAINED" 			DATE, 
	"GRADE" 					VARCHAR2(3), 
	"SAL_ADMIN_PLAN" 			VARCHAR2(4), 
	"GVT_CURR_AGCY_EMPL" 		VARCHAR2(1), 
	"GVT_CURR_FED_EMPL" 		VARCHAR2(1), 
	"GVT_HIGH_PAY_PLAN" 		VARCHAR2(2), 
	"GVT_HIGH_GRADE" 			VARCHAR2(3), 
	"GVT_PREV_AGCY_EMPL" 		VARCHAR2(1), 
	"GVT_PREV_FED_EMPL" 		VARCHAR2(1), 
	"GVT_SEP_INCENTIVE" 		VARCHAR2(1), 
	"GVT_SEP_INCENT_DT" 		DATE, 
	"GVT_TENURE" 				VARCHAR2(1), 
	"GVT_PAY_PLAN" 				VARCHAR2(2), 
	"BARG_UNIT" 				VARCHAR2(4), 
	"LASTUPDDTTM" 				TIMESTAMP (6), 
	"BIRTHPLACE" 				VARCHAR2(30), 
	"BIRTHCOUNTRY" 				VARCHAR2(3), 
	"BIRTHSTATE" 				VARCHAR2(6), 
	"HIGHEST_EDUC_LVL" 			VARCHAR2(2), 
	"FT_STUDENT" 				VARCHAR2(1), 
	"LANG_CD" 					VARCHAR2(3), 
	"ALTER_EMPLID" 				VARCHAR2(11), 
	"ADDRESS1_AC" 				VARCHAR2(55), 
	"ADDRESS2_AC" 				VARCHAR2(55), 
	"ADDRESS3_AC" 				VARCHAR2(55), 
	"CITY_AC" 					VARCHAR2(30), 
	"HE_ERI" 					VARCHAR2(6)
);

--------------------------------------------------------
--  DDL for Table PS_POSITION_DATA
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PS_POSITION_DATA" 
(
	"POSITION_NBR" 					VARCHAR2(8) NOT NULL ENABLE, 
	"EFFDT" 						DATE NOT NULL ENABLE, 
	"EFF_STATUS" 					VARCHAR2(1) NOT NULL ENABLE, 
	"DESCR" 						VARCHAR2(30) NOT NULL ENABLE, 
	"DESCRSHORT" 					VARCHAR2(10) NOT NULL ENABLE, 
	"ACTION" 						VARCHAR2(3) NOT NULL ENABLE, 
	"ACTION_REASON" 				VARCHAR2(3) NOT NULL ENABLE, 
	"ACTION_DT" 					DATE, 
	"BUSINESS_UNIT" 				VARCHAR2(5) NOT NULL ENABLE, 
	"DEPTID" 						VARCHAR2(10) NOT NULL ENABLE, 
	"JOBCODE" 						VARCHAR2(6) NOT NULL ENABLE, 
	"POSN_STATUS" 					VARCHAR2(1) NOT NULL ENABLE, 
	"STATUS_DT" 					DATE, 
	"BUDGETED_POSN" 				VARCHAR2(1) NOT NULL ENABLE, 
	"CONFIDENTIAL_POSN" 			VARCHAR2(1) NOT NULL ENABLE, 
	"KEY_POSITION" 					VARCHAR2(1) NOT NULL ENABLE, 
	"JOB_SHARE" 					VARCHAR2(1) NOT NULL ENABLE, 
	"MAX_HEAD_COUNT" 				NUMBER(*,0) NOT NULL ENABLE, 
	"UPDATE_INCUMBENTS" 			VARCHAR2(1) NOT NULL ENABLE, 
	"REPORTS_TO" 					VARCHAR2(8) NOT NULL ENABLE, 
	"REPORT_DOTTED_LINE" 			VARCHAR2(8) NOT NULL ENABLE, 
	"ORGCODE" 						VARCHAR2(60) NOT NULL ENABLE, 
	"ORGCODE_FLAG" 					VARCHAR2(1) NOT NULL ENABLE, 
	"LOCATION" 						VARCHAR2(10) NOT NULL ENABLE, 
	"MAIL_DROP" 					VARCHAR2(50) NOT NULL ENABLE, 
	"COUNTRY_CODE" 					VARCHAR2(3) NOT NULL ENABLE, 
	"PHONE" 						VARCHAR2(24) NOT NULL ENABLE, 
	"COMPANY" 						VARCHAR2(3) NOT NULL ENABLE, 
	"STD_HOURS" 					NUMBER(6,2) NOT NULL ENABLE, 
	"STD_HRS_FREQUENCY" 			VARCHAR2(5) NOT NULL ENABLE, 
	"UNION_CD" 						VARCHAR2(3) NOT NULL ENABLE, 
	"SHIFT" 						VARCHAR2(1) NOT NULL ENABLE, 
	"REG_TEMP" 						VARCHAR2(1) NOT NULL ENABLE, 
	"FULL_PART_TIME" 				VARCHAR2(1) NOT NULL ENABLE, 
	"MON_HRS" 						NUMBER(4,2) NOT NULL ENABLE, 
	"TUES_HRS" 						NUMBER(4,2) NOT NULL ENABLE, 
	"WED_HRS" 						NUMBER(4,2) NOT NULL ENABLE, 
	"THURS_HRS" 					NUMBER(4,2) NOT NULL ENABLE, 
	"FRI_HRS" 						NUMBER(4,2) NOT NULL ENABLE, 
	"SAT_HRS" 						NUMBER(4,2) NOT NULL ENABLE, 
	"SUN_HRS" 						NUMBER(4,2) NOT NULL ENABLE, 
	"BARG_UNIT" 					VARCHAR2(4) NOT NULL ENABLE, 
	"GVT_PAY_PLAN" 					VARCHAR2(2) NOT NULL ENABLE, 
	"SEASONAL" 						VARCHAR2(1) NOT NULL ENABLE, 
	"TRN_PROGRAM" 					VARCHAR2(6) NOT NULL ENABLE, 
	"LANGUAGE_SKILL" 				VARCHAR2(2) NOT NULL ENABLE, 
	"MANAGER_LEVEL" 				VARCHAR2(2) NOT NULL ENABLE, 
	"FLSA_STATUS" 					VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_WIP_STATUS" 				VARCHAR2(3) NOT NULL ENABLE, 
	"GVT_STATUS_TYPE" 				VARCHAR2(3) NOT NULL ENABLE, 
	"GVT_WORK_SCHED" 				VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_SUB_AGENCY" 				VARCHAR2(2) NOT NULL ENABLE, 
	"GVT_DT_POSN_ESTAB" 			DATE, 
	"GVT_COMP_AREA" 				VARCHAR2(2) NOT NULL ENABLE, 
	"GVT_COMP_LEVEL" 				VARCHAR2(4) NOT NULL ENABLE, 
	"GVT_ORG_TTL_CD" 				VARCHAR2(4) NOT NULL ENABLE, 
	"GVT_ORG_TTL_DESCR" 			VARCHAR2(70) NOT NULL ENABLE, 
	"GVT_DRUG_TEST_REQ" 			VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_FUND_SOURCE" 				VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_INTEL_POSN" 				VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_LEO_POSITION" 				VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_MOB_POSN_IND" 				VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_PROC_INTEG_PSN" 			VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_PRESIDENT_APPT" 			VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_NTE_DATE" 					DATE, 
	"GVT_OCC_SERIES" 				VARCHAR2(4) NOT NULL ENABLE, 
	"GVT_PAR_NBR" 					VARCHAR2(15) NOT NULL ENABLE, 
	"GVT_PAREN_TITLE" 				VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_PERF_PLAN" 				VARCHAR2(8) NOT NULL ENABLE, 
	"GVT_POI" 						VARCHAR2(4) NOT NULL ENABLE, 
	"GVT_POSN_LOC" 					VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_POSN_OCCUPIED" 			VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_POSN_SENS_CD" 				VARCHAR2(1) NOT NULL ENABLE, 
	"SECURITY_CLEARANCE" 			VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_STAFF_LINE" 				VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_LAST_AUDIT_DT" 			DATE, 
	"GVT_AUDITED_BY_ID" 			VARCHAR2(11) NOT NULL ENABLE, 
	"GVT_OBLIGATED_TO" 				VARCHAR2(11) NOT NULL ENABLE, 
	"GVT_OBLIG_EXPIR_DT" 			DATE, 
	"GVT_TARGET_GRADE" 				VARCHAR2(2) NOT NULL ENABLE, 
	"GVT_PI_UPD_IND" 				VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_EXEC_FIN_DISCL" 			VARCHAR2(1) NOT NULL ENABLE, 
	"GVT_EMP_FIN_INT" 				VARCHAR2(1) NOT NULL ENABLE, 
	"REG_REGION" 					VARCHAR2(5) NOT NULL ENABLE, 
	"CLASS_INDC" 					VARCHAR2(1) NOT NULL ENABLE, 
	"ENCUMBER_INDC" 				VARCHAR2(1) NOT NULL ENABLE, 
	"FTE" 							NUMBER(7,6) NOT NULL ENABLE, 
	"POSITION_POOL_ID" 				VARCHAR2(3) NOT NULL ENABLE, 
	"EG_ACADEMIC_RANK" 				VARCHAR2(3) NOT NULL ENABLE, 
	"EG_GROUP" 						VARCHAR2(6) NOT NULL ENABLE, 
	"ENCUMB_SAL_OPTN" 				VARCHAR2(3) NOT NULL ENABLE, 
	"ENCUMB_SAL_AMT" 				NUMBER(18,3) NOT NULL ENABLE, 
	"HEALTH_CERTIFICATE" 			VARCHAR2(1) NOT NULL ENABLE, 
	"SIGN_AUTHORITY" 				VARCHAR2(1) NOT NULL ENABLE, 
	"ADDS_TO_FTE_ACTUAL" 			VARCHAR2(1) NOT NULL ENABLE, 
	"SAL_ADMIN_PLAN" 				VARCHAR2(4) NOT NULL ENABLE, 
	"GRADE" 						VARCHAR2(3) NOT NULL ENABLE, 
	"GRADE_FROM" 					VARCHAR2(3) NOT NULL ENABLE, 
	"STEP_FROM" 					NUMBER(*,0) NOT NULL ENABLE, 
	"GRADE_TO" 						VARCHAR2(3) NOT NULL ENABLE, 
	"STEP_TO" 						NUMBER(*,0) NOT NULL ENABLE, 
	"STEP" 							NUMBER(*,0) NOT NULL ENABLE, 
	"JOB_PROFILE_ID" 				VARCHAR2(8) NOT NULL ENABLE, 
	"PKG_TEMPLATE_ID" 				VARCHAR2(10) NOT NULL ENABLE, 
	"PKG_RULE_ID" 					VARCHAR2(10) NOT NULL ENABLE, 
	"SUPV_LVL_ID" 					VARCHAR2(8) NOT NULL ENABLE, 
	"INCLUDE_SALPLN_FLG" 			VARCHAR2(1) NOT NULL ENABLE, 
	"POSN_DATA_MESSAGE" 			VARCHAR2(1) NOT NULL ENABLE, 
	"HE_MED_OFF_IND" 				VARCHAR2(1) NOT NULL ENABLE, 
	"HE_SE_TYPE" 					VARCHAR2(1) NOT NULL ENABLE, 
	"HE_TERM_ID" 					VARCHAR2(2) NOT NULL ENABLE, 
	"HE_POS_SUBJECT_TO" 			VARCHAR2(1) NOT NULL ENABLE, 
	"HE_ACTIVITY_FUNC" 				VARCHAR2(4) NOT NULL ENABLE, 
	"HE_REASON_CODE" 				VARCHAR2(1) NOT NULL ENABLE, 
	"FUNCTION_CD" 					VARCHAR2(2) NOT NULL ENABLE, 
	"DESCRLONG" 					LONG
);

CREATE INDEX HHS_HR.PS_POSITION_DATA_IDX1 ON HHS_HR.PS_POSITION_DATA (POSITION_NBR ASC);

CREATE INDEX HHS_HR.PS_POSITION_DATA_IDX2 ON HHS_HR.PS_POSITION_DATA (BUSINESS_UNIT ASC, JOBCODE ASC);

CREATE INDEX HHS_HR.PS_POSITION_DATA_IDX3 ON HHS_HR.PS_POSITION_DATA (POSITION_NBR ASC, EFFDT ASC);

CREATE INDEX HHS_HR.PS_POSITION_DATA_IDX4 ON HHS_HR.PS_POSITION_DATA (JOBCODE ASC);

CREATE INDEX HHS_HR.PS_POSITION_DATA_IDX5 ON HHS_HR.PS_POSITION_DATA (EFF_STATUS ASC);

--------------------------------------------------------
--  DDL for Table PS_SAL_GRADE_TBL
--------------------------------------------------------
CREATE TABLE "HHS_HR"."PS_SAL_GRADE_TBL" 
(
	"SETID" 					VARCHAR2(5) NOT NULL ENABLE, 
	"SAL_ADMIN_PLAN" 			VARCHAR2(4) NOT NULL ENABLE, 
	"GRADE" 					VARCHAR2(3) NOT NULL ENABLE, 
	"EFFDT" 					DATE NOT NULL ENABLE, 
	"EFF_STATUS" 				VARCHAR2(1) NOT NULL ENABLE, 
	"DESCR" 					VARCHAR2(30) NOT NULL ENABLE, 
	"DESCRSHORT" 				VARCHAR2(10) NOT NULL ENABLE, 
	"SALARY_MATRIX_CD" 			VARCHAR2(5) NOT NULL ENABLE, 
	"CURRENCY_CD" 				VARCHAR2(3) NOT NULL ENABLE, 
	"MIN_RT_HOURLY" 			NUMBER(18,6) NOT NULL ENABLE, 
	"MID_RT_HOURLY" 			NUMBER(18,6) NOT NULL ENABLE, 
	"MAX_RT_HOURLY" 			NUMBER(18,6) NOT NULL ENABLE, 
	"MIN_RT_MONTHLY" 			NUMBER(18,3) NOT NULL ENABLE, 
	"MID_RT_MONTHLY" 			NUMBER(18,3) NOT NULL ENABLE, 
	"MAX_RT_MONTHLY" 			NUMBER(18,3) NOT NULL ENABLE, 
	"MIN_RT_ANNUAL" 			NUMBER(18,3) NOT NULL ENABLE, 
	"MID_RT_ANNUAL" 			NUMBER(18,3) NOT NULL ENABLE, 
	"MAX_RT_ANNUAL" 			NUMBER(18,3) NOT NULL ENABLE, 
	"STEP_INCREM_TYPE" 			VARCHAR2(1) NOT NULL ENABLE, 
	"STEP_INCREM_ACCUM" 		VARCHAR2(3) NOT NULL ENABLE, 
	"MIN_RT_DAILY" 				NUMBER(18,3) NOT NULL ENABLE, 
	"MID_RT_DAILY" 				NUMBER(18,3) NOT NULL ENABLE, 
	"MAX_RT_DAILY" 				NUMBER(18,3) NOT NULL ENABLE, 
	"LABOR_AGREEMENT" 			VARCHAR2(6) NOT NULL ENABLE, 
	"EMPL_CTG" 					VARCHAR2(6) NOT NULL ENABLE, 
	"EMPL_CTG_L1" 				VARCHAR2(6) NOT NULL ENABLE, 
	"EMPL_CTG_L2" 				VARCHAR2(6) NOT NULL ENABLE, 
	"GVT_MAX_RT_BIWK" 			NUMBER(9,2) NOT NULL ENABLE, 
	"GVT_MID_RT_BIWK" 			NUMBER(9,2) NOT NULL ENABLE, 
	"GVT_MIN_RT_BIWK" 			NUMBER(9,2) NOT NULL ENABLE, 
	"GRADE_TITLE_JPN" 			VARCHAR2(60) NOT NULL ENABLE, 
	"MIN_YRS_GRADE" 			NUMBER(*,0) NOT NULL ENABLE, 
	"MAX_YRS_GRADE" 			NUMBER(*,0) NOT NULL ENABLE, 
	"MIN_GRD_AGE" 				NUMBER(*,0) NOT NULL ENABLE, 
	"REVIEW_COUNT" 				NUMBER(*,0) NOT NULL ENABLE, 
	"ELIGIBILITY_POINTS" 		NUMBER(4,1) NOT NULL ENABLE, 
	"REG_REGION" 				VARCHAR2(5) NOT NULL ENABLE, 
	"JOB_PROFILE_ID" 			VARCHAR2(8) NOT NULL ENABLE
);