
----------------------------------
-- grant for HHS_HR_RW_ROLE
----------------------------------

GRANT SELECT ON HHS_HR.EHRP_JOB_REQ_VW TO HHS_HR_RW_ROLE;
GRANT SELECT ON HHS_HR.EHRP_LOCATION_VW TO HHS_HR_RW_ROLE;
GRANT SELECT ON HHS_HR.EHRP_POSITION_VW TO HHS_HR_RW_ROLE;
GRANT SELECT ON HHS_HR.EHRP_JO_RPL_VW TO HHS_HR_RW_ROLE;



----------------------------------
-- grant for HHS_HR_DEV_ROLE
----------------------------------

GRANT SELECT ON HHS_HR.EHRP_JOB_REQ_VW TO HHS_HR_DEV_ROLE;
GRANT SELECT ON HHS_HR.EHRP_LOCATION_VW TO HHS_HR_DEV_ROLE;
GRANT SELECT ON HHS_HR.EHRP_POSITION_VW TO HHS_HR_DEV_ROLE;
GRANT SELECT ON HHS_HR.EHRP_JO_RPL_VW TO HHS_HR_DEV_ROLE;
