
----------------------------------
-- grant for HHS_HR_RW_ROLE
----------------------------------

GRANT SELECT ON HHS_HR.VW_EHRP_JOB_REQ TO HHS_HR_RW_ROLE;
GRANT SELECT ON HHS_HR.VW_EHRP_LOCATION TO HHS_HR_RW_ROLE;
GRANT SELECT ON HHS_HR.VW_EHRP_POSITION TO HHS_HR_RW_ROLE;
GRANT SELECT ON HHS_HR.VW_EHRP_JO_RPL TO HHS_HR_RW_ROLE;



----------------------------------
-- grant for HHS_HR_DEV_ROLE
----------------------------------

GRANT SELECT ON HHS_HR.VW_EHRP_JOB_REQ TO HHS_HR_DEV_ROLE;
GRANT SELECT ON HHS_HR.VW_EHRP_LOCATION TO HHS_HR_DEV_ROLE;
GRANT SELECT ON HHS_HR.VW_EHRP_POSITION TO HHS_HR_DEV_ROLE;
GRANT SELECT ON HHS_HR.VW_EHRP_JO_RPL TO HHS_HR_DEV_ROLE;
