GRANT SELECT ON HHS_HR.PS_DEPT_TBL TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_HE_RECRUIT_EWIT TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_HRS_JO_LOC TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_HRS_JO_NAME TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_HRS_JO_POSN TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_HRS_JO_RPL TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_HRS_JO_RQMT TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_HRS_JOB_OPENING TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_HRS_LOCATION_I TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_JOBCODE_TBL TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_POSITION_DATA TO HHS_WHRSC_HR;s
GRANT SELECT ON HHS_HR.PS_SAL_GRADE_TBL TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_HE_JO_APPR_COMM TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.EMPLOYEE_LOOKUP TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.ADMINISTRATIVE_CODE TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_PERSONAL_DATA_VW TO HHS_WHRSC_HR;


