-------------------------------------
--EHRP VIEWS
-------------------------------------

-------------------
--VW_EHRP_JOB_REQ
-------------------
CREATE OR REPLACE VIEW VW_EHRP_JOB_REQ
AS
SELECT JOB.HRS_JOB_OPENING_ID,
	JOB.ORIGINATOR_ID,
	JOB.OPEN_DT,
	JOB.STATUS_CODE,
	JOB.BUSINESS_UNIT,
	JOB.DEPTID AS JOB_DEPTID,
	JOB.GVT_RECR_OFFICE,
	JOB.GVT_SEL_OFFICIAL,
	JOB.STATUS_DT,
	JOB.OPENINGS_TARGET,
	JOB.SETID_DEPT,
	JOB.COMPANY,
	JOB.HRS_PRM_JOBCODE,
	JOB.HRS_PRM_POSITION,
	JOB.HRS_PRM_LOCATION,
	JOB.HRS_PRM_PST_TITLE,
	JOB.DESIRED_START_DT,
	JOB.AUTHORIZATION_DT,
	JOB.COUNTRY,
	JOB.GVT_STAFF_SPCLST,
	JOB.GVT_CONSIDER_AREA,
	JOB.HRS_G_JO_TYPE AS GVT_RQSN_TYPE,
	JOB.HRS_ROW_ADD_OPRID AS INITIATOR_OPRID,
	JOB.HE_COMMENTS,
	JOP.POSITION_NBR,
	JOP.HRS_JO_PRM_PSN_FLG,
	POS.REPORTS_TO AS POS_REPORTS_TO,
	POS.LOCATION AS POS_LOCATION,
	POS.STD_HOURS AS POS_STD_HOURS,
	POS.BARG_UNIT AS POS_BARG_UNIT,
	POS.GVT_PAY_PLAN AS POS_GVT_PAY_PLAN,
	POS.GVT_WORK_SCHED AS POS_GVT_WORK_SCHED,
	POS.GRADE AS POS_GRADE,
	POS.DESCR AS POSITION_DESCR,
	POS.STEP AS POS_STEP,
	POS.GVT_ORG_TTL_DESCR AS POS_GVT_ORG_TTL_DESCR,
	POS.GVT_DRUG_TEST_REQ AS POS_GVT_DRUG_TEST_REQ,
	POS.GVT_OCC_SERIES AS POS_GVT_OCC_SERIES,
	POS.GVT_POSN_SENS_CD AS POS_GVT_POSN_SENS_CD,
	POS.SECURITY_CLEARANCE AS POS_SECURITY_CLEARANCE,
	POS.GVT_EMP_FIN_INT AS POS_GVT_EMP_FIN_INT,
	POS.LANGUAGE_SKILL AS POS_LANGUAGE_SKILL,
	SAL.MIN_RT_ANNUAL AS SAL_MIN_RT_ANNUAL,
	SAL.MAX_RT_ANNUAL AS SAL_MAX_RT_ANNUAL,
	LOCI.SETID AS LOC_SETID,
	JOL.HRS_JO_PRM_LOC_FLG,
	LOCI.LOCATION AS LOC_LOCATION,
	LOCI.COUNTRY AS LOC_COUNTRY,
	LOCI.STATE AS LOC_STATE,
	LOCI.DESCR AS LOC_DESCR,
	LOCI.DESCRSHORT AS LOC_DESCRSHORT,
	JC.SETID AS JC_SETID,
	RQMT.JOBCODE AS JC_JOBCODE,
	RQMT.HRS_JO_PRM_JCD_FLG AS GVT_PRIMARY_JCODE,
	RQMT.HRS_JO_RQMT_SEQ,
	JC.DESCR AS JC_DESCR,
	JC.REG_REGION AS JC_REG_REGION,
	RQMT.FULL_PART_TIME AS JC_FULL_PART_TIME,
	JC.REG_TEMP as JC_REGTEMP,
	JC.STD_HOURS AS JC_STD_HOURS,
	RQMT.SHIFT AS JC_SHIFT,
	RQMT.HRS_JO_MIN_RT AS GVT_RQSN_SAL_FROM,
	RQMT.HRS_JO_MAX_RT AS GVT_RQSN_SAL_TO,
	RQMT.PAY_FREQ_ABBRV AS JC_PAY_FREQ_ABBRV,
	JC.CURRENCY_CD AS JC_CURRENCY_CD,
	JC.SAL_ADMIN_PLAN AS JC_SAL_ADMIN_PLAN,
	JC.GVT_PAY_PLAN AS JC_GVT_PAY_PLAN,
	JC.GVT_OCC_SERIES AS JC_GVT_OCC_SERIES,
	JC.GRADE AS JC_GRADE,
	JC.STEP AS JC_STEP,
	JC.GVT_OFFICIAL_DESCR AS JC_GVT_OFFICIAL_DESCR,
	JC.GVT_ORG_TTL_DESCR AS JC_GVT_ORG_TTL_DESCR,
	RQMT.MANAGER_LEVEL AS JC_MANAGER_LEVEL,
	RQMT.FLSA_STATUS AS JC_FLSA_STATUS,
	RQMT.GVT_SUMMER_APPT AS JC_GVT_SUMMER_APPT,
	RQMT.GVT_NTE_DATE AS JC_GVT_NTE_DATE,
	RQMT.GVT_NTE_DAYS AS JC_GVT_NTE_DAYS,
	RQMT.GVT_LEO_POSITION AS JC_GVT_LEO_POSITION,
	RQMT.GVT_POSN_SENS_CD AS JC_GVT_POSN_SENS_CD,
	RQMT.GVT_TYPE_OF_APPT AS JC_GVT_TYPE_OF_APPT,
	JC.GVT_EMP_FIN_INT AS JC_GVT_EMP_FIN_INT,
	JC.GVT_EXEC_FIN_DISCL AS JC_GVT_EXEC_FIN_DISCL,
	JC.GVT_TARGET_GRADE AS JC_GVT_TARGET_GRADE,
	DEPT.SETID AS DEPT_SETID,
	DEPT.DEPTID,
	DEPT.DESCR AS DEPT_DESCR,
	DEPT.GVT_PAR_LINE2,
	DEPT.GVT_PAR_DESCR2,
	DEPT.GVT_PAR_LINE3,
	DEPT.GVT_PAR_DESCR3,
	DEPT.GVT_PAR_LINE4,
	DEPT.GVT_PAR_DESCR4,
	DEPT.GVT_PAR_LINE5,
	DEPT.GVT_PAR_DESCR5,
	EWIT.HE_COMP_ALLOWANCE,
	EWIT.HE_DENTIST_PAY,
	EWIT.HE_NON_STANDARD_PA,
	EWIT.HE_POSITION_DESCR,
	EWIT.HE_RECRUIT_INCENT,
	EWIT.HE_RELOCATIONBONUS,
	EWIT.ACCT_CD AS CAN
FROM PS_HRS_JOB_OPENING JOB
	,PS_HRS_JO_POSN JOP
	,PS_POSITION_DATA POS
	,PS_DEPT_TBL DEPT
	,PS_HRS_JO_RQMT RQMT
	,PS_JOBCODE_TBL JC
	,PS_HRS_JO_LOC JOL
	,PS_HRS_LOCATION_I LOCI
	,PS_SAL_GRADE_TBL SAL
	,PS_HE_RECRUIT_EWIT EWIT
WHERE JOB.HRS_JOB_OPENING_ID = JOP.HRS_JOB_OPENING_ID
	AND POS.POSITION_NBR = JOP.POSITION_NBR
	AND POS.EFFDT = 
		(
			SELECT MAX(EFFDT)
			FROM PS_POSITION_DATA
			WHERE POSITION_NBR = POS.POSITION_NBR
				AND EFFDT <= JOB.OPEN_DT
		)
	AND DEPT.SETID = JOB.BUSINESS_UNIT
	AND DEPT.DEPTID = JOB.DEPTID
	AND DEPT.EFFDT =
		(
			SELECT MAX(EFFDT)
			FROM PS_DEPT_TBL
			WHERE SETID = DEPT.SETID
				AND DEPTID = DEPT.DEPTID
				AND EFFDT <= JOB.OPEN_DT
		)
	AND RQMT.HRS_JOB_OPENING_ID = JOB.HRS_JOB_OPENING_ID
	AND JC.SETID = DEPT.SETID
	AND JC.JOBCODE = POS.JOBCODE
	AND JC.EFFDT =
		(
			SELECT MAX(EFFDT)
			FROM PS_JOBCODE_TBL
			WHERE SETID = JC.SETID
				AND JOBCODE = JC.JOBCODE
				AND EFFDT <= JOB.OPEN_DT
		)
	AND JOL.HRS_JOB_OPENING_ID = JOB.HRS_JOB_OPENING_ID
	AND LOCI.LOCATION = JOL.LOCATION
	AND LOCI.EFFDT =
		(
			SELECT MAX(EFFDT)
			FROM PS_HRS_LOCATION_I
			WHERE LOCATION = LOCI.LOCATION
				AND EFFDT <= JOB.OPEN_DT
		)
	AND SAL.SETID = POS.GVT_PAY_PLAN
	AND SAL.SAL_ADMIN_PLAN = POS.SAL_ADMIN_PLAN
	AND SAL.GRADE = POS.GRADE
	AND SAL.EFFDT =
		(
			SELECT MAX(EFFDT)
			FROM PS_SAL_GRADE_TBL
			WHERE SETID = SAL.SETID
				AND SAL_ADMIN_PLAN = SAL.SAL_ADMIN_PLAN
				AND GRADE = SAL.GRADE
				AND EFFDT <= JOB.OPEN_DT
		)
	AND EWIT.HRS_JOB_OPENING_ID = JOB.HRS_JOB_OPENING_ID
	AND POS.EFF_STATUS = 'A'
	AND DEPT.EFF_STATUS = 'A'
	AND JC.EFF_STATUS = 'A'
	AND SAL.EFF_STATUS = 'A'
	AND JOB.OPEN_DT >= TO_DATE('01/01/2018','mm/dd/yyyy');

----------------
--VW_EHRP_LOCATION
----------------
CREATE OR REPLACE VIEW VW_EHRP_LOCATION
AS
SELECT HRS_JOB_OPENING_ID,
	SETID,
	LOCATION,
	EFFDT,
	COUNTRY,
	STATE,
	DESCR,
	DESCRSHORT,
	OPENINGS_TARGET,
	HRS_JO_PRM_LOC_FLG
FROM
	(
		SELECT JOL.HRS_JOB_OPENING_ID,
			LOCI.SETID,
			LOCI.LOCATION,
			LOCI.EFFDT,
			LOCI.COUNTRY,
			LOCI.STATE,
			LOCI.DESCR,
			LOCI.DESCRSHORT,
			JOL.OPENINGS_TARGET,
			JOL.HRS_JO_PRM_LOC_FLG,
			RANK() OVER (PARTITION BY LOCI.LOCATION ORDER BY LOCI.EFFDT DESC) AS RANK
		FROM PS_HRS_JOB_OPENING JOB
			JOIN PS_HRS_JO_LOC JOL
				ON JOL.HRS_JOB_OPENING_ID = JOB.HRS_JOB_OPENING_ID
			JOIN PS_HRS_LOCATION_I LOCI
				ON LOCI.LOCATION = JOL.LOCATION
					AND LOCI.EFFDT <= JOB.OPEN_DT
	)
WHERE RANK = 1;

----------------
--VW_EHRP_POSITION
----------------
CREATE OR REPLACE VIEW VW_EHRP_POSITION
AS
SELECT HRS_JOB_OPENING_ID,
	POSITION_NBR,
	HRS_JO_PRM_PSN_FLG,
	EFFDT,
	EFF_STATUS,
	JOBCODE,
	COMPANY,
	BUSINESS_UNIT,
	LOCATION,
	REG_REGION,
	FULL_PART_TIME,
	REG_TEMP,
	STD_HOURS,
	SHIFT,
	SAL_ADMIN_PLAN,
	MANAGER_LEVEL,
	REPORTS_TO,
	STATUS_DT,
	FLSA_STATUS,
	GVT_NTE_DATE,
	GVT_LEO_POSITION,
	POSITION_DESCR,
	STEP,
	GRADE,
	BARG_UNIT,
	GVT_PAY_PLAN,
	GVT_TARGET_GRADE,
	GVT_WORK_SCHED,
	GVT_ORG_TTL_DESCR,
	GVT_DRUG_TEST_REQ,
	GVT_OCC_SERIES,
	GVT_POSN_SENS_CD,
	SECURITY_CLEARANCE,
	GVT_EMP_FIN_INT,
	GVT_EXEC_FIN_DISCL,
	LANGUAGE_SKILL
FROM
	(
		SELECT JOP.HRS_JOB_OPENING_ID,
			JOP.POSITION_NBR,
			JOP.HRS_JO_PRM_PSN_FLG,
			POS.EFFDT,
			POS.EFF_STATUS,
			POS.JOBCODE,
			POS.COMPANY,
			POS.BUSINESS_UNIT,
			POS.LOCATION,
			POS.REG_REGION,
			POS.FULL_PART_TIME,
			POS.REG_TEMP,
			POS.STD_HOURS,
			POS.SHIFT,
			POS.SAL_ADMIN_PLAN,
			POS.MANAGER_LEVEL,
			POS.REPORTS_TO,
			POS.STATUS_DT,
			POS.FLSA_STATUS,
			POS.GVT_NTE_DATE,
			POS.GVT_LEO_POSITION,
			POS.DESCR AS POSITION_DESCR,
			POS.STEP,
			POS.GRADE,
			POS.BARG_UNIT,
			POS.GVT_PAY_PLAN,
			POS.GVT_TARGET_GRADE,
			POS.GVT_WORK_SCHED,
			POS.GVT_ORG_TTL_DESCR,
			POS.GVT_DRUG_TEST_REQ,
			POS.GVT_OCC_SERIES,
			POS.GVT_POSN_SENS_CD,
			POS.SECURITY_CLEARANCE,
			POS.GVT_EMP_FIN_INT,
			POS.GVT_EXEC_FIN_DISCL,
			POS.LANGUAGE_SKILL,
			RANK() OVER (PARTITION BY POS.POSITION_NBR ORDER BY POS.EFFDT DESC) AS RANK
		FROM PS_HRS_JOB_OPENING JOB
			JOIN PS_HRS_JO_POSN JOP
				ON JOP.HRS_JOB_OPENING_ID = JOB.HRS_JOB_OPENING_ID
			JOIN PS_POSITION_DATA POS
				ON POS.POSITION_NBR = JOP.POSITION_NBR
			AND POS.EFFDT <= JOB.OPEN_DT
	)
WHERE RANK = 1;

-----------------------
--VW_EHRP_JO_RPL
----------------------
CREATE OR REPLACE VIEW VW_EHRP_JO_RPL
AS
SELECT RPL.HRS_JOB_OPENING_ID,
	RPL.EMPLID,
	PER.NAME,
	RPL.HE_VACATED_DT
FROM PS_HRS_JO_RPL RPL
	LEFT JOIN PS_PERSONAL_DATA_VW PER
		ON RPL.EMPLID = PER.EMPLID;
