
----------------------------------
-- grant for HHS_BIIS_VIEW_ROLE
----------------------------------
GRANT SELECT ON HISTDBA.DES_BIIS_PERSON_MV TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON HISTDBA.DUTY_STATION TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON HISTDBA.LEGAL_AUTHORITY TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON HISTDBA.NATURE_OF_ACTION TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON HISTDBA.SAC_HIST_EXTENDED TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON HISTDBA.MD715_SERIES TO HHS_BIIS_VIEW_ROLE;


----------------------------------
-- grant for HHS_BIIS_OWNER_ROLE
----------------------------------
GRANT DELETE, INSERT, SELECT, UPDATE ON HISTDBA.DES_BIIS_PERSON_MV TO HHS_BIIS_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HISTDBA.DUTY_STATION TO HHS_BIIS_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HISTDBA.LEGAL_AUTHORITY TO HHS_BIIS_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HISTDBA.NATURE_OF_ACTION TO HHS_BIIS_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HISTDBA.SAC_HIST_EXTENDED TO HHS_BIIS_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HISTDBA.MD715_SERIES TO HHS_BIIS_OWNER_ROLE;

