
----------------------------------
-- grant for HHS_HR_RW_ROLE
----------------------------------

GRANT EXECUTE ON HHS_HR.REF_DATA_PKS TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.EHRP_REF_DATA_PKS TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.BIIS_PERSON TO HHS_HR_RW_ROLE;


----------------------------------
-- grant for HHS_HR_DEV_ROLE
----------------------------------

GRANT EXECUTE ON HHS_HR.REF_DATA_PKS TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.EHRP_REF_DATA_PKS TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.BIIS_PERSON TO HHS_HR_DEV_ROLE;
