
----------------------------------
-- grant for HHS_HR_RW_ROLE
----------------------------------

GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_ANNOUNCEMENT_DETAIL TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_ANNOUNCEMENT_APPT_TYPE TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_ANNOUNCEMENT_WORK_SCHED TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_ANNOUNCEMENT_LOCATION TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_APPLICATION_DETAIL TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_APPLICATION_DOCUMENT TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_APPLICATION_LOCATION TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_APPLICATION_ELIGIBILITY TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_APPLICANT_PHONE TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_APPLICATION_RATING TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CERTIFICATE TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CERTIFICATE_APP TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_NEW_HIRE TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REQUEST_DETAIL TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REQUEST_APPT_TYPE TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REQUEST_SPECIALTY TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REQUEST_POSITION TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REQUEST_LOCATION TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REQUEST_WORK_SCHED TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REQUEST_VACANCY TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REVIEW_DETAIL TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_TASK_DETAIL TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_VACANCY_DETAIL TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_VACANCY_CUSTOMER TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_VACANCY_ELIGIBILITY TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_VACANCY_POSITION TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_VACANCY_SPECIALTY TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_VACANCY_DOCUMENT TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_VACANCY_REQUEST TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_TIME_TO_STAFF TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_TIME_TO_OFFER TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_ANNOUNCEMENT TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_ANN_LOCATION TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_ANN_REVIEW TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_CERTIFICATE TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_NEW_HIRE TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.AREA_CONSIDERATION TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_TIME_TO_STAFF_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_TIME_TO_OFFER_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_ANNOUNCEMENT_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_ANN_LOCATION_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_ANN_REVIEW_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_CERTIFICATE_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_NEW_HIRE_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_OFFER TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_STAFF TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_OFFER_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_STAFF_STG TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_CERTIFICATE TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_CERTIFICATE_STG TO HHS_HR_RW_ROLE;



----------------------------------
-- grant for HHS_HR_DEV_ROLE
----------------------------------

GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_ANNOUNCEMENT_DETAIL TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_ANNOUNCEMENT_APPT_TYPE TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_ANNOUNCEMENT_WORK_SCHED TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_ANNOUNCEMENT_LOCATION TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_APPLICATION_DETAIL TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_APPLICATION_DOCUMENT TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_APPLICATION_LOCATION TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_APPLICATION_ELIGIBILITY TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_APPLICANT_PHONE TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_APPLICATION_RATING TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CERTIFICATE TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CERTIFICATE_APP TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_NEW_HIRE TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REQUEST_DETAIL TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REQUEST_APPT_TYPE TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REQUEST_SPECIALTY TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REQUEST_POSITION TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REQUEST_LOCATION TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REQUEST_WORK_SCHED TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REQUEST_VACANCY TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_REVIEW_DETAIL TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_TASK_DETAIL TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_VACANCY_DETAIL TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_VACANCY_CUSTOMER TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_VACANCY_ELIGIBILITY TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_VACANCY_POSITION TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_VACANCY_SPECIALTY TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_VACANCY_DOCUMENT TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_VACANCY_REQUEST TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_TIME_TO_STAFF TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_TIME_TO_OFFER TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_ANNOUNCEMENT TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_ANN_LOCATION TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_ANN_REVIEW TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_CERTIFICATE TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_NEW_HIRE TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.AREA_CONSIDERATION TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_TIME_TO_STAFF_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_TIME_TO_OFFER_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_ANNOUNCEMENT_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_ANN_LOCATION_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_ANN_REVIEW_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_CERTIFICATE_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_IHS_VAC_NEW_HIRE_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_OFFER TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_STAFF TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_OFFER_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_TIME_TO_STAFF_STG TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_CERTIFICATE TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.DSS_CDC_CERTIFICATE_STG TO HHS_HR_DEV_ROLE;


----------------------------------
-- grant for IHS
----------------------------------
-- required to generate stored procedure SP_MONITOR_USAS
GRANT SELECT ON HHS_HR.DSS_IHS_VAC_ANNOUNCEMENT TO HHS_IHS_HR WITH GRANT OPTION;
GRANT SELECT ON HHS_HR.DSS_IHS_VAC_CERTIFICATE TO HHS_IHS_HR WITH GRANT OPTION;
GRANT SELECT ON HHS_HR.DSS_IHS_VAC_NEW_HIRE TO HHS_IHS_HR WITH GRANT OPTION;
GRANT SELECT ON HHS_HR.DSS_IHS_VAC_ANN_LOCATION TO HHS_IHS_HR WITH GRANT OPTION;
GRANT SELECT ON HHS_HR.DSS_IHS_VAC_ANN_REVIEW TO HHS_IHS_HR WITH GRANT OPTION;
GRANT SELECT ON HHS_HR.ADMINISTRATIVE_CODE TO HHS_IHS_HR WITH GRANT OPTION;
GRANT SELECT ON HHS_HR.DUTY_STATION TO HHS_IHS_HR WITH GRANT OPTION;

-- required to execute stored procedure SP_MONITOR_USAS
GRANT SELECT ON HHS_HR.DSS_IHS_VAC_ANNOUNCEMENT TO BIZFLOW;
GRANT SELECT ON HHS_HR.DSS_IHS_VAC_CERTIFICATE TO BIZFLOW;
GRANT SELECT ON HHS_HR.DSS_IHS_VAC_NEW_HIRE TO BIZFLOW;
GRANT SELECT ON HHS_HR.DSS_IHS_VAC_ANN_REVIEW TO BIZFLOW;
GRANT SELECT ON HHS_HR.DSS_IHS_VAC_ANN_LOCATION TO BIZFLOW;