

------------------------------------
-- Backout statement
------------------------------------
/*

DROP TABLE EHRP.PS_DEPT_TBL;
DROP TABLE EHRP.PS_HE_EWIT_DEPT_1;
DROP TABLE EHRP.PS_HE_RECRUIT_EWIT;
DROP TABLE EHRP.PS_HRS_JO_LOC;
DROP TABLE EHRP.PS_HRS_JO_NAME;
DROP TABLE EHRP.PS_HRS_JO_POSN;
DROP TABLE EHRP.PS_HRS_JO_RPL;
DROP TABLE EHRP.PS_HRS_JO_RQMT;
DROP TABLE EHRP.PS_HRS_JOB_OPENING;
DROP TABLE EHRP.PS_JOBCODE_TBL;
DROP TABLE EHRP.PS_POSITION_DATA;
DROP TABLE EHRP.PS_SAL_GRADE_TBL;

-- view in real BIIS, but recreated as table due to permission
DROP TABLE EHRP.PS_HRS_LOCATION_I;
DROP TABLE EHRP.PS_PERSONAL_DATA_VW;

*/


SET DEFINE OFF;

--=============================================================================
-- TABLE definition
--=============================================================================


-------------------------------------
--PS_DEPT_TBL DDL
-------------------------------------
CREATE TABLE EHRP.PS_DEPT_TBL 
(
	SETID VARCHAR2(5 BYTE) NOT NULL 
	, DEPTID VARCHAR2(10 BYTE) NOT NULL 
	, EFFDT DATE NOT NULL 
	, EFF_STATUS VARCHAR2(1 BYTE) NOT NULL 
	, DESCR VARCHAR2(30 BYTE) NOT NULL 
	, DESCRSHORT VARCHAR2(10 BYTE) NOT NULL 
	, COMPANY VARCHAR2(3 BYTE) NOT NULL 
	, SETID_LOCATION VARCHAR2(5 BYTE) NOT NULL 
	, LOCATION VARCHAR2(10 BYTE) NOT NULL 
	, TAX_LOCATION_CD VARCHAR2(10 BYTE) NOT NULL 
	, MANAGER_ID VARCHAR2(11 BYTE) NOT NULL 
	, MANAGER_POSN VARCHAR2(8 BYTE) NOT NULL 
	, BUDGET_YR_END_DT NUMBER(*, 0) NOT NULL 
	, BUDGET_LVL VARCHAR2(1 BYTE) NOT NULL 
	, GL_EXPENSE VARCHAR2(35 BYTE) NOT NULL 
	, EEO4_FUNCTION VARCHAR2(2 BYTE) NOT NULL 
	, CAN_IND_SECTOR VARCHAR2(3 BYTE) NOT NULL 
	, ACCIDENT_INS VARCHAR2(3 BYTE) NOT NULL 
	, SI_ACCIDENT_NUM VARCHAR2(15 BYTE) NOT NULL 
	, HAZARD VARCHAR2(4 BYTE) NOT NULL 
	, ESTABID VARCHAR2(12 BYTE) NOT NULL 
	, RISKCD VARCHAR2(6 BYTE) NOT NULL 
	, GRADE VARCHAR2(3 BYTE) NOT NULL 
	, GVT_DESCR40 VARCHAR2(40 BYTE) NOT NULL 
	, GVT_SUB_AGENCY VARCHAR2(2 BYTE) NOT NULL 
	, GVT_PAR_LINE2 VARCHAR2(10 BYTE) NOT NULL 
	, GVT_PAR_LINE3 VARCHAR2(10 BYTE) NOT NULL 
	, GVT_PAR_LINE4 VARCHAR2(10 BYTE) NOT NULL 
	, GVT_PAR_LINE5 VARCHAR2(10 BYTE) NOT NULL 
	, GVT_PAR_DESCR2 VARCHAR2(40 BYTE) NOT NULL 
	, GVT_PAR_DESCR3 VARCHAR2(40 BYTE) NOT NULL 
	, GVT_PAR_DESCR4 VARCHAR2(40 BYTE) NOT NULL 
	, GVT_PAR_DESCR5 VARCHAR2(40 BYTE) NOT NULL 
	, FTE_EDIT_INDC VARCHAR2(1 BYTE) NOT NULL 
	, DEPT_TENURE_FLG VARCHAR2(1 BYTE) NOT NULL 
	, TL_DISTRIB_INFO VARCHAR2(1 BYTE) NOT NULL 
	, USE_BUDGETS VARCHAR2(1 BYTE) NOT NULL 
	, USE_ENCUMBRANCES VARCHAR2(1 BYTE) NOT NULL 
	, USE_DISTRIBUTION VARCHAR2(1 BYTE) NOT NULL 
	, BUDGET_DEPTID VARCHAR2(10 BYTE) NOT NULL 
	, HP_STATS_DEPT_CD VARCHAR2(3 BYTE) NOT NULL 
	, HP_STATS_FACULTY VARCHAR2(5 BYTE) NOT NULL 
	, MANAGER_NAME VARCHAR2(30 BYTE) NOT NULL 
	, ACCOUNTING_OWNER VARCHAR2(30 BYTE) NOT NULL 
	, COUNTRY_GRP VARCHAR2(18 BYTE) NOT NULL 
	, CLASS_UNIT_NZL VARCHAR2(5 BYTE) NOT NULL 
	, ORG_UNIT_AUS VARCHAR2(4 BYTE) NOT NULL 
	, WORK_SECTOR_AUS VARCHAR2(1 BYTE) NOT NULL 
	, APS_AGENT_CD_AUS NUMBER(*, 0) NOT NULL 
	, IND_COMMITTEE_BEL VARCHAR2(3 BYTE) NOT NULL 
	, NACE_CD_BEL VARCHAR2(10 BYTE) NOT NULL 
);

/




-------------------------------------
--PS_HE_EWIT_DEPT_1 DDL
-------------------------------------
CREATE TABLE EHRP.PS_HE_EWIT_DEPT_1 
(
	SETID VARCHAR2(5 BYTE) NOT NULL 
	, DEPTID VARCHAR2(10 BYTE) NOT NULL 
	, DESCR VARCHAR2(30 BYTE) NOT NULL 
	, GVT_PAR_LINE2 VARCHAR2(10 BYTE) NOT NULL 
	, GVT_PAR_DESCR2 VARCHAR2(40 BYTE) NOT NULL 
	, GVT_PAR_LINE3 VARCHAR2(10 BYTE) NOT NULL 
	, GVT_PAR_DESCR3 VARCHAR2(40 BYTE) NOT NULL 
	, GVT_PAR_LINE4 VARCHAR2(10 BYTE) NOT NULL 
	, GVT_PAR_DESCR4 VARCHAR2(40 BYTE) NOT NULL 
	, GVT_PAR_LINE5 VARCHAR2(10 BYTE) NOT NULL 
	, GVT_PAR_DESCR5 VARCHAR2(40 BYTE) NOT NULL 
);

/




-------------------------------------
--PS_HE_RECRUIT_EWIT DDL
-------------------------------------
CREATE TABLE EHRP.PS_HE_RECRUIT_EWIT 
(
	HRS_JOB_OPENING_ID NUMBER(15, 0) NOT NULL 
	, HE_COMP_ALLOWANCE VARCHAR2(1 BYTE) NOT NULL 
	, HE_DENTIST_PAY VARCHAR2(1 BYTE) NOT NULL 
	, HE_NON_STANDARD_PA VARCHAR2(1 BYTE) NOT NULL 
	, HE_POSITION_DESCR VARCHAR2(1 BYTE) NOT NULL 
	, HE_RECRUIT_INCENT VARCHAR2(1 BYTE) NOT NULL 
	, HE_RELOCATIONBONUS VARCHAR2(1 BYTE) NOT NULL 
	, ACCT_CD VARCHAR2(25 BYTE) NOT NULL 
);

/




-------------------------------------
--PS_HRS_JO_LOC DDL
-------------------------------------
CREATE TABLE EHRP.PS_HRS_JO_LOC 
(
	HRS_JOB_OPENING_ID NUMBER(15, 0) NOT NULL 
	, LOCATION VARCHAR2(10 BYTE) NOT NULL 
	, OPENINGS_TARGET NUMBER(*, 0) NOT NULL 
	, HRS_JO_PRM_LOC_FLG VARCHAR2(1 BYTE) NOT NULL 
	, HRS_ROW_ADD_DTTM TIMESTAMP(6) 
	, HRS_ROW_ADD_OPRID VARCHAR2(30 BYTE) NOT NULL 
	, HRS_ROW_UPD_DTTM TIMESTAMP(6) 
	, HRS_ROW_UPD_OPRID VARCHAR2(30 BYTE) NOT NULL 
);

/




-------------------------------------
--PS_HRS_JO_NAME DDL
-------------------------------------
CREATE TABLE EHRP.PS_HRS_JO_NAME 
(
	HRS_JOB_OPENING_ID NUMBER(15, 0) NOT NULL 
	, SEQUENCE_NBR NUMBER(*, 0) NOT NULL 
	, NAME VARCHAR2(50 BYTE) NOT NULL 
	, HRS_ROW_ADD_DTTM TIMESTAMP(6) 
	, HRS_ROW_ADD_OPRID VARCHAR2(30 BYTE) NOT NULL 
	, HRS_ROW_UPD_DTTM TIMESTAMP(6) 
	, HRS_ROW_UPD_OPRID VARCHAR2(30 BYTE) NOT NULL 
)
;

/




-------------------------------------
--PS_HRS_JO_POSN DDL
-------------------------------------
CREATE TABLE EHRP.PS_HRS_JO_POSN 
(
	HRS_JOB_OPENING_ID NUMBER(15, 0) NOT NULL 
	, POSITION_NBR VARCHAR2(8 BYTE) NOT NULL 
	, HRS_JO_PRM_PSN_FLG VARCHAR2(1 BYTE) NOT NULL 
	, HRS_ROW_ADD_DTTM TIMESTAMP(6) 
	, HRS_ROW_ADD_OPRID VARCHAR2(30 BYTE) NOT NULL 
	, HRS_ROW_UPD_DTTM TIMESTAMP(6) 
	, HRS_ROW_UPD_OPRID VARCHAR2(30 BYTE) NOT NULL 
);

/




-------------------------------------
--PS_HRS_JO_RPL DDL
-------------------------------------
CREATE TABLE EHRP.PS_HRS_JO_RPL 
(
	HRS_JOB_OPENING_ID NUMBER(15, 0) NOT NULL 
	, EMPLID VARCHAR2(11 BYTE) NOT NULL 
	, HE_VACATED_DT DATE 
	, HRS_ROW_ADD_DTTM TIMESTAMP(6) 
	, HRS_ROW_ADD_OPRID VARCHAR2(30 BYTE) NOT NULL 
	, HRS_ROW_UPD_DTTM TIMESTAMP(6) 
	, HRS_ROW_UPD_OPRID VARCHAR2(30 BYTE) NOT NULL 
);

/




-------------------------------------
--PS_HRS_JO_RQMT DDL
-------------------------------------
CREATE TABLE EHRP.PS_HRS_JO_RQMT 
(
	HRS_JOB_OPENING_ID NUMBER(15, 0) NOT NULL 
	, HRS_JO_RQMT_SEQ NUMBER(*, 0) NOT NULL 
	, JOBCODE VARCHAR2(6 BYTE) NOT NULL 
	, HRS_JO_PRM_JCD_FLG VARCHAR2(1 BYTE) NOT NULL 
	, GVT_NUM_APPS_CONS NUMBER(*, 0) NOT NULL 
	, GVT_RQSN_CERT_NBR VARCHAR2(10 BYTE) NOT NULL 
	, GVT_RQSN_CERT_SRC VARCHAR2(1 BYTE) NOT NULL 
	, GVT_RQSN_CERT_STS VARCHAR2(1 BYTE) NOT NULL 
	, DT_DUE DATE 
	, DT_ISSUED DATE 
	, DT_RECVD DATE 
	, DT_REQUESTED DATE 
	, DT_RETURNED DATE 
	, GVT_DT_EXTENDED DATE 
	, GVT_DT_RET_FRM_SO DATE 
	, GVT_DT_SENT_TO_SO DATE 
	, REG_REGION VARCHAR2(5 BYTE) NOT NULL 
	, FULL_PART_TIME VARCHAR2(1 BYTE) NOT NULL 
	, REG_TEMP VARCHAR2(1 BYTE) NOT NULL 
	, BEGIN_DT DATE 
	, END_DT DATE 
	, STD_HOURS NUMBER(6, 2) NOT NULL 
	, STD_HRS_FREQUENCY VARCHAR2(5 BYTE) NOT NULL 
	, SHIFT VARCHAR2(1 BYTE) NOT NULL 
	, HRS_JO_MIN_RT NUMBER(21, 6) NOT NULL 
	, HRS_JO_MAX_RT NUMBER(21, 6) NOT NULL 
	, PAY_FREQ_ABBRV VARCHAR2(1 BYTE) NOT NULL 
	, CURRENCY_CD VARCHAR2(3 BYTE) NOT NULL 
	, SAL_ADMIN_PLAN VARCHAR2(4 BYTE) NOT NULL 
	, GRADE_FROM VARCHAR2(3 BYTE) NOT NULL 
	, GRADE_TO VARCHAR2(3 BYTE) NOT NULL 
	, STEP_FROM NUMBER(*, 0) NOT NULL 
	, STEP_TO NUMBER(*, 0) NOT NULL 
	, HRS_TRAVEL_PERCENT VARCHAR2(1 BYTE) NOT NULL 
	, MANAGER_LEVEL VARCHAR2(2 BYTE) NOT NULL 
	, FLSA_STATUS VARCHAR2(1 BYTE) NOT NULL 
	, GVT_SUMMER_APPT VARCHAR2(1 BYTE) NOT NULL 
	, GVT_NTE_DATE DATE 
	, GVT_NTE_DAYS NUMBER(*, 0) NOT NULL 
	, GVT_LEO_POSITION VARCHAR2(1 BYTE) NOT NULL 
	, GVT_POSN_SENS_CD VARCHAR2(1 BYTE) NOT NULL 
	, GVT_TYPE_OF_APPT VARCHAR2(2 BYTE) NOT NULL 
	, HRS_ROW_ADD_DTTM TIMESTAMP(6) 
	, HRS_ROW_ADD_OPRID VARCHAR2(30 BYTE) NOT NULL 
	, HRS_ROW_UPD_DTTM TIMESTAMP(6) 
	, HRS_ROW_UPD_OPRID VARCHAR2(30 BYTE) NOT NULL 
);

/




-------------------------------------
--PS_HRS_JOB_OPENING DDL
-------------------------------------
CREATE TABLE EHRP.PS_HRS_JOB_OPENING 
(
	HRS_JOB_OPENING_ID NUMBER(15, 0) NOT NULL 
	, HRS_RCRT_TMPL_ID NUMBER(15, 0) NOT NULL 
	, HRS_JO_TYPE VARCHAR2(1 BYTE) NOT NULL 
	, REFERRAL_PGM_ID VARCHAR2(12 BYTE) NOT NULL 
	, ORIGINATOR_ID VARCHAR2(11 BYTE) NOT NULL 
	, MANAGER_ID VARCHAR2(11 BYTE) NOT NULL 
	, RECRUITER_ID VARCHAR2(11 BYTE) NOT NULL 
	, GVT_SEL_OFFICIAL VARCHAR2(11 BYTE) NOT NULL 
	, OPEN_DT DATE 
	, CLOSE_DT DATE 
	, STATUS_CODE VARCHAR2(3 BYTE) NOT NULL 
	, STATUS_REASON VARCHAR2(3 BYTE) NOT NULL 
	, STATUS_DT DATE NOT NULL 
	, HRS_OPENING_LIMIT VARCHAR2(1 BYTE) NOT NULL 
	, OPENINGS_CNT NUMBER(*, 0) NOT NULL 
	, OPENINGS_TARGET NUMBER(*, 0) NOT NULL 
	, HOT_JOB VARCHAR2(1 BYTE) NOT NULL 
	, BUSINESS_UNIT VARCHAR2(5 BYTE) NOT NULL 
	, SETID_DEPT VARCHAR2(5 BYTE) NOT NULL 
	, DEPTID VARCHAR2(10 BYTE) NOT NULL 
	, COMPANY VARCHAR2(3 BYTE) NOT NULL 
	, HRS_PRM_JOBCODE VARCHAR2(6 BYTE) NOT NULL 
	, HRS_PRM_POSITION VARCHAR2(8 BYTE) NOT NULL 
	, HRS_PRM_LOCATION VARCHAR2(10 BYTE) NOT NULL 
	, HRS_PRM_LOC_AREA NUMBER(15, 0) NOT NULL 
	, HRS_PRM_PST_TITLE VARCHAR2(200 BYTE) NOT NULL 
	, DESIRED_START_DT DATE 
	, WC_COUNCIL_ID VARCHAR2(9 BYTE) NOT NULL 
	, ENCUMB_DT_INDC VARCHAR2(1 BYTE) NOT NULL 
	, PROJECTED_FILL_DT DATE 
	, AUTHORIZATION_DT DATE 
	, ESTABID VARCHAR2(12 BYTE) NOT NULL 
	, COUNTRY VARCHAR2(3 BYTE) NOT NULL 
	, CITIZENSHIP_STATUS VARCHAR2(1 BYTE) NOT NULL 
	, MIN_AGE NUMBER(*, 0) NOT NULL 
	, MAX_AGE NUMBER(*, 0) NOT NULL 
	, SEX VARCHAR2(1 BYTE) NOT NULL 
	, HRS_CONTACT_ID NUMBER(15, 0) NOT NULL 
	, GVT_STAFF_SPCLST VARCHAR2(11 BYTE) NOT NULL 
	, GVT_CONSIDER_AREA VARCHAR2(1 BYTE) NOT NULL 
	, GVT_DRAFT_STATUS VARCHAR2(1 BYTE) NOT NULL 
	, HRS_G_JO_TYPE VARCHAR2(1 BYTE) NOT NULL 
	, JOB_FAMILY VARCHAR2(6 BYTE) NOT NULL 
	, HRS_ROW_ADD_DTTM TIMESTAMP(6) 
	, HRS_ROW_ADD_OPRID VARCHAR2(30 BYTE) NOT NULL 
	, HRS_ROW_UPD_DTTM TIMESTAMP(6) 
	, HRS_ROW_UPD_OPRID VARCHAR2(30 BYTE) NOT NULL 
	, GVT_RECR_OFFICE VARCHAR2(10 BYTE) NOT NULL 
	, HE_APPROVALO_OPRID VARCHAR2(30 BYTE) NOT NULL 
	, HE_COMMENTS LONG 
);

/




-------------------------------------
--PS_JOBCODE_TBL DDL
-------------------------------------
CREATE TABLE EHRP.PS_JOBCODE_TBL 
(
	SETID VARCHAR2(5 BYTE) NOT NULL 
	, JOBCODE VARCHAR2(6 BYTE) NOT NULL 
	, EFFDT DATE NOT NULL 
	, EFF_STATUS VARCHAR2(1 BYTE) NOT NULL 
	, DESCR VARCHAR2(30 BYTE) NOT NULL 
	, DESCRSHORT VARCHAR2(10 BYTE) NOT NULL 
	, JOB_FUNCTION VARCHAR2(3 BYTE) NOT NULL 
	, SETID_SALARY VARCHAR2(5 BYTE) NOT NULL 
	, SAL_ADMIN_PLAN VARCHAR2(4 BYTE) NOT NULL 
	, GRADE VARCHAR2(3 BYTE) NOT NULL 
	, STEP NUMBER(*, 0) NOT NULL 
	, MANAGER_LEVEL VARCHAR2(2 BYTE) NOT NULL 
	, SURVEY_SALARY NUMBER(*, 0) NOT NULL 
	, SURVEY_JOB_CODE VARCHAR2(8 BYTE) NOT NULL 
	, UNION_CD VARCHAR2(3 BYTE) NOT NULL 
	, RETRO_RATE NUMBER(6, 4) NOT NULL 
	, RETRO_PERCENT NUMBER(6, 4) NOT NULL 
	, CURRENCY_CD VARCHAR2(3 BYTE) NOT NULL 
	, STD_HOURS NUMBER(6, 2) NOT NULL 
	, STD_HRS_FREQUENCY VARCHAR2(5 BYTE) NOT NULL 
	, COMP_FREQUENCY VARCHAR2(5 BYTE) NOT NULL 
	, WORKERS_COMP_CD VARCHAR2(4 BYTE) NOT NULL 
	, JOB_FAMILY VARCHAR2(6 BYTE) NOT NULL 
	, JOB_KNOWHOW_POINTS NUMBER(*, 0) NOT NULL 
	, JOB_ACCNTAB_POINTS NUMBER(*, 0) NOT NULL 
	, JOB_PROBSLV_POINTS NUMBER(*, 0) NOT NULL 
	, JOB_POINTS_TOTAL NUMBER(*, 0) NOT NULL 
	, JOB_KNOWHOW_PCT NUMBER(4, 1) NOT NULL 
	, JOB_ACCNTAB_PCT NUMBER(4, 1) NOT NULL 
	, JOB_PROBSLV_PCT NUMBER(4, 1) NOT NULL 
	, REG_TEMP VARCHAR2(1 BYTE) NOT NULL 
	, DIRECTLY_TIPPED VARCHAR2(1 BYTE) NOT NULL 
	, MED_CHKUP_REQ VARCHAR2(1 BYTE) NOT NULL 
	, FLSA_STATUS VARCHAR2(1 BYTE) NOT NULL 
	, EEO1CODE VARCHAR2(1 BYTE) NOT NULL 
	, EEO4CODE VARCHAR2(1 BYTE) NOT NULL 
	, EEO5CODE VARCHAR2(2 BYTE) NOT NULL 
	, EEO6CODE VARCHAR2(1 BYTE) NOT NULL 
	, EEO_JOB_GROUP VARCHAR2(4 BYTE) NOT NULL 
	, US_SOC_CD VARCHAR2(10 BYTE) NOT NULL 
	, IPEDSSCODE VARCHAR2(1 BYTE) NOT NULL 
	, US_OCC_CD VARCHAR2(3 BYTE) NOT NULL 
	, CAN_PAYEQ_JOB_CLS VARCHAR2(3 BYTE) NOT NULL 
	, CAN_NOC_CD VARCHAR2(4 BYTE) NOT NULL 
	, SEASONAL VARCHAR2(1 BYTE) NOT NULL 
	, BPS_ACTIVITY_CD VARCHAR2(6 BYTE) NOT NULL 
	, FUNCTION_CD VARCHAR2(2 BYTE) NOT NULL 
	, BA_CD VARCHAR2(3 BYTE) NOT NULL 
	, TECHNICAL VARCHAR2(1 BYTE) NOT NULL 
	, MED_SURV_REQ VARCHAR2(1 BYTE) NOT NULL 
	, EMP_CATEGRY_FRA VARCHAR2(3 BYTE) NOT NULL 
	, ACTIVITY_TYPE_FRA VARCHAR2(3 BYTE) NOT NULL 
	, INSEE_CD_FRA VARCHAR2(4 BYTE) NOT NULL 
	, JOB_CTG_FRA_CD VARCHAR2(2 BYTE) NOT NULL 
	, UK_SOC_CD VARCHAR2(2 BYTE) NOT NULL 
	, GVT_PAY_PLAN VARCHAR2(2 BYTE) NOT NULL 
	, GVT_OCC_SERIES VARCHAR2(4 BYTE) NOT NULL 
	, TRN_PROGRAM VARCHAR2(6 BYTE) NOT NULL 
	, COMPANY VARCHAR2(3 BYTE) NOT NULL 
	, GVT_FUNC_CLASS VARCHAR2(2 BYTE) NOT NULL 
	, GVT_POSN_TITLE_CD VARCHAR2(4 BYTE) NOT NULL 
	, GVT_OFFICIAL_DESCR VARCHAR2(70 BYTE) NOT NULL 
	, GVT_ORG_TTL_CD VARCHAR2(4 BYTE) NOT NULL 
	, GVT_ORG_TTL_DESCR VARCHAR2(70 BYTE) NOT NULL 
	, GVT_PAY_BASIS VARCHAR2(2 BYTE) NOT NULL 
	, GVT_SUB_AGENCY VARCHAR2(2 BYTE) NOT NULL 
	, GVT_POI VARCHAR2(4 BYTE) NOT NULL 
	, GVT_PAREN_TITLE VARCHAR2(1 BYTE) NOT NULL 
	, GVT_OPM_CERT_NBR VARCHAR2(8 BYTE) NOT NULL 
	, GVT_POSN_CLASS_STD VARCHAR2(254 BYTE) NOT NULL 
	, GVT_POSN_SENS_CD VARCHAR2(1 BYTE) NOT NULL 
	, GVT_IA_ACTIONS VARCHAR2(1 BYTE) NOT NULL 
	, GVT_EXEC_FIN_DISCL VARCHAR2(1 BYTE) NOT NULL 
	, GVT_EMP_FIN_INT VARCHAR2(1 BYTE) NOT NULL 
	, GVT_PATCOB_CD VARCHAR2(1 BYTE) NOT NULL 
	, GVT_CLS_STANDARD VARCHAR2(15 BYTE) NOT NULL 
	, GVT_CLASSIFIER_ID VARCHAR2(11 BYTE) NOT NULL 
	, GVT_DT_CLASSIFIED DATE 
	, BARG_UNIT VARCHAR2(4 BYTE) NOT NULL 
	, GVT_FUND_SOURCE VARCHAR2(1 BYTE) NOT NULL 
	, GVT_LEO_POSITION VARCHAR2(1 BYTE) NOT NULL 
	, GVT_PERF_PLAN VARCHAR2(8 BYTE) NOT NULL 
	, GVT_TARGET_GRADE VARCHAR2(2 BYTE) NOT NULL 
	, GVT_PI_UPD_IND VARCHAR2(1 BYTE) NOT NULL 
	, ENCUMBER_INDC VARCHAR2(1 BYTE) NOT NULL 
	, POSN_MGMT_INDC VARCHAR2(1 BYTE) NOT NULL 
	, EG_ACADEMIC_RANK VARCHAR2(3 BYTE) NOT NULL 
	, EG_GROUP VARCHAR2(6 BYTE) NOT NULL 
	, HP_STATS_DUTIES VARCHAR2(2 BYTE) NOT NULL 
	, HP_STATS_RPT_FLAG VARCHAR2(1 BYTE) NOT NULL 
	, ENCUMB_SAL_OPTN VARCHAR2(3 BYTE) NOT NULL 
	, ENCUMB_SAL_AMT NUMBER(18, 3) NOT NULL 
	, INAIL_CODE VARCHAR2(11 BYTE) NOT NULL 
	, ASCO_CD_AUS VARCHAR2(6 BYTE) NOT NULL 
	, PKG_TEMPLATE_ID VARCHAR2(10 BYTE) NOT NULL 
	, PKG_RULE_ID VARCHAR2(10 BYTE) NOT NULL 
	, FUNCTION_AUS VARCHAR2(1 BYTE) NOT NULL 
	, ANN_CNTACT_HRS_AUS NUMBER(6, 2) NOT NULL 
	, TEACH_WEEKS_AUS NUMBER(*, 0) NOT NULL 
	, CASUAL_TYPE_AUS VARCHAR2(1 BYTE) NOT NULL 
	, WORK_DAY_HOURS NUMBER(6, 2) NOT NULL 
	, FA_PAY_PROGRAM VARCHAR2(3 BYTE) NOT NULL 
	, ELECTION_GROUP VARCHAR2(5 BYTE) NOT NULL 
	, LABOR_AGREEMENT VARCHAR2(6 BYTE) NOT NULL 
	, FP_PROF_CATG VARCHAR2(3 BYTE) NOT NULL 
	, FP_JOB_FMLY VARCHAR2(4 BYTE) NOT NULL 
	, FP_OFF_COLAG VARCHAR2(1 BYTE) NOT NULL 
	, FP_MATRIX_TYP VARCHAR2(3 BYTE) NOT NULL 
	, FP_MATRIX_CD VARCHAR2(4 BYTE) NOT NULL 
	, FP_BUSINESS_CD VARCHAR2(4 BYTE) NOT NULL 
	, FP_JOBCD_ACC VARCHAR2(1 BYTE) NOT NULL 
	, FP_ATCH_AREA VARCHAR2(4 BYTE) NOT NULL 
	, FP_JOB_TYP VARCHAR2(2 BYTE) NOT NULL 
	, FP_AUTO_RATFY VARCHAR2(1 BYTE) NOT NULL 
	, LAST_UPDATE_DATE DATE 
	, REG_REGION VARCHAR2(5 BYTE) NOT NULL 
	, SAL_RANGE_MIN_RATE NUMBER(18, 6) NOT NULL 
	, SAL_RANGE_MID_RATE NUMBER(18, 6) NOT NULL 
	, SAL_RANGE_MAX_RATE NUMBER(18, 6) NOT NULL 
	, SAL_RANGE_CURRENCY VARCHAR2(3 BYTE) NOT NULL 
	, SAL_RANGE_FREQ VARCHAR2(5 BYTE) NOT NULL 
	, JOB_PROFILE_ID VARCHAR2(8 BYTE) NOT NULL 
	, DESCRLONG LONG 
);

/

CREATE INDEX EHRP.PS_JOBCODE_TBL_IDX1 ON EHRP.PS_JOBCODE_TBL (SETID ASC, JOBCODE ASC, EFFDT ASC);
CREATE INDEX EHRP.PS_JOBCODE_TBL_IDX2 ON EHRP.PS_JOBCODE_TBL (EFF_STATUS ASC);

/




-------------------------------------
--PS_POSITION_DATA DDL
-------------------------------------
CREATE TABLE EHRP.PS_POSITION_DATA 
(
	POSITION_NBR VARCHAR2(8 BYTE) NOT NULL 
	, EFFDT DATE NOT NULL 
	, EFF_STATUS VARCHAR2(1 BYTE) NOT NULL 
	, DESCR VARCHAR2(30 BYTE) NOT NULL 
	, DESCRSHORT VARCHAR2(10 BYTE) NOT NULL 
	, ACTION VARCHAR2(3 BYTE) NOT NULL 
	, ACTION_REASON VARCHAR2(3 BYTE) NOT NULL 
	, ACTION_DT DATE 
	, BUSINESS_UNIT VARCHAR2(5 BYTE) NOT NULL 
	, DEPTID VARCHAR2(10 BYTE) NOT NULL 
	, JOBCODE VARCHAR2(6 BYTE) NOT NULL 
	, POSN_STATUS VARCHAR2(1 BYTE) NOT NULL 
	, STATUS_DT DATE 
	, BUDGETED_POSN VARCHAR2(1 BYTE) NOT NULL 
	, CONFIDENTIAL_POSN VARCHAR2(1 BYTE) NOT NULL 
	, KEY_POSITION VARCHAR2(1 BYTE) NOT NULL 
	, JOB_SHARE VARCHAR2(1 BYTE) NOT NULL 
	, MAX_HEAD_COUNT NUMBER(*, 0) NOT NULL 
	, UPDATE_INCUMBENTS VARCHAR2(1 BYTE) NOT NULL 
	, REPORTS_TO VARCHAR2(8 BYTE) NOT NULL 
	, REPORT_DOTTED_LINE VARCHAR2(8 BYTE) NOT NULL 
	, ORGCODE VARCHAR2(60 BYTE) NOT NULL 
	, ORGCODE_FLAG VARCHAR2(1 BYTE) NOT NULL 
	, LOCATION VARCHAR2(10 BYTE) NOT NULL 
	, MAIL_DROP VARCHAR2(50 BYTE) NOT NULL 
	, COUNTRY_CODE VARCHAR2(3 BYTE) NOT NULL 
	, PHONE VARCHAR2(24 BYTE) NOT NULL 
	, COMPANY VARCHAR2(3 BYTE) NOT NULL 
	, STD_HOURS NUMBER(6, 2) NOT NULL 
	, STD_HRS_FREQUENCY VARCHAR2(5 BYTE) NOT NULL 
	, UNION_CD VARCHAR2(3 BYTE) NOT NULL 
	, SHIFT VARCHAR2(1 BYTE) NOT NULL 
	, REG_TEMP VARCHAR2(1 BYTE) NOT NULL 
	, FULL_PART_TIME VARCHAR2(1 BYTE) NOT NULL 
	, MON_HRS NUMBER(4, 2) NOT NULL 
	, TUES_HRS NUMBER(4, 2) NOT NULL 
	, WED_HRS NUMBER(4, 2) NOT NULL 
	, THURS_HRS NUMBER(4, 2) NOT NULL 
	, FRI_HRS NUMBER(4, 2) NOT NULL 
	, SAT_HRS NUMBER(4, 2) NOT NULL 
	, SUN_HRS NUMBER(4, 2) NOT NULL 
	, BARG_UNIT VARCHAR2(4 BYTE) NOT NULL 
	, GVT_PAY_PLAN VARCHAR2(2 BYTE) NOT NULL 
	, SEASONAL VARCHAR2(1 BYTE) NOT NULL 
	, TRN_PROGRAM VARCHAR2(6 BYTE) NOT NULL 
	, LANGUAGE_SKILL VARCHAR2(2 BYTE) NOT NULL 
	, MANAGER_LEVEL VARCHAR2(2 BYTE) NOT NULL 
	, FLSA_STATUS VARCHAR2(1 BYTE) NOT NULL 
	, GVT_WIP_STATUS VARCHAR2(3 BYTE) NOT NULL 
	, GVT_STATUS_TYPE VARCHAR2(3 BYTE) NOT NULL 
	, GVT_WORK_SCHED VARCHAR2(1 BYTE) NOT NULL 
	, GVT_SUB_AGENCY VARCHAR2(2 BYTE) NOT NULL 
	, GVT_DT_POSN_ESTAB DATE 
	, GVT_COMP_AREA VARCHAR2(2 BYTE) NOT NULL 
	, GVT_COMP_LEVEL VARCHAR2(4 BYTE) NOT NULL 
	, GVT_ORG_TTL_CD VARCHAR2(4 BYTE) NOT NULL 
	, GVT_ORG_TTL_DESCR VARCHAR2(70 BYTE) NOT NULL 
	, GVT_DRUG_TEST_REQ VARCHAR2(1 BYTE) NOT NULL 
	, GVT_FUND_SOURCE VARCHAR2(1 BYTE) NOT NULL 
	, GVT_INTEL_POSN VARCHAR2(1 BYTE) NOT NULL 
	, GVT_LEO_POSITION VARCHAR2(1 BYTE) NOT NULL 
	, GVT_MOB_POSN_IND VARCHAR2(1 BYTE) NOT NULL 
	, GVT_PROC_INTEG_PSN VARCHAR2(1 BYTE) NOT NULL 
	, GVT_PRESIDENT_APPT VARCHAR2(1 BYTE) NOT NULL 
	, GVT_NTE_DATE DATE 
	, GVT_OCC_SERIES VARCHAR2(4 BYTE) NOT NULL 
	, GVT_PAR_NBR VARCHAR2(15 BYTE) NOT NULL 
	, GVT_PAREN_TITLE VARCHAR2(1 BYTE) NOT NULL 
	, GVT_PERF_PLAN VARCHAR2(8 BYTE) NOT NULL 
	, GVT_POI VARCHAR2(4 BYTE) NOT NULL 
	, GVT_POSN_LOC VARCHAR2(1 BYTE) NOT NULL 
	, GVT_POSN_OCCUPIED VARCHAR2(1 BYTE) NOT NULL 
	, GVT_POSN_SENS_CD VARCHAR2(1 BYTE) NOT NULL 
	, SECURITY_CLEARANCE VARCHAR2(1 BYTE) NOT NULL 
	, GVT_STAFF_LINE VARCHAR2(1 BYTE) NOT NULL 
	, GVT_LAST_AUDIT_DT DATE 
	, GVT_AUDITED_BY_ID VARCHAR2(11 BYTE) NOT NULL 
	, GVT_OBLIGATED_TO VARCHAR2(11 BYTE) NOT NULL 
	, GVT_OBLIG_EXPIR_DT DATE 
	, GVT_TARGET_GRADE VARCHAR2(2 BYTE) NOT NULL 
	, GVT_PI_UPD_IND VARCHAR2(1 BYTE) NOT NULL 
	, GVT_EXEC_FIN_DISCL VARCHAR2(1 BYTE) NOT NULL 
	, GVT_EMP_FIN_INT VARCHAR2(1 BYTE) NOT NULL 
	, REG_REGION VARCHAR2(5 BYTE) NOT NULL 
	, CLASS_INDC VARCHAR2(1 BYTE) NOT NULL 
	, ENCUMBER_INDC VARCHAR2(1 BYTE) NOT NULL 
	, FTE NUMBER(7, 6) NOT NULL 
	, POSITION_POOL_ID VARCHAR2(3 BYTE) NOT NULL 
	, EG_ACADEMIC_RANK VARCHAR2(3 BYTE) NOT NULL 
	, EG_GROUP VARCHAR2(6 BYTE) NOT NULL 
	, ENCUMB_SAL_OPTN VARCHAR2(3 BYTE) NOT NULL 
	, ENCUMB_SAL_AMT NUMBER(18, 3) NOT NULL 
	, HEALTH_CERTIFICATE VARCHAR2(1 BYTE) NOT NULL 
	, SIGN_AUTHORITY VARCHAR2(1 BYTE) NOT NULL 
	, ADDS_TO_FTE_ACTUAL VARCHAR2(1 BYTE) NOT NULL 
	, SAL_ADMIN_PLAN VARCHAR2(4 BYTE) NOT NULL 
	, GRADE VARCHAR2(3 BYTE) NOT NULL 
	, GRADE_FROM VARCHAR2(3 BYTE) NOT NULL 
	, STEP_FROM NUMBER(*, 0) NOT NULL 
	, GRADE_TO VARCHAR2(3 BYTE) NOT NULL 
	, STEP_TO NUMBER(*, 0) NOT NULL 
	, STEP NUMBER(*, 0) NOT NULL 
	, JOB_PROFILE_ID VARCHAR2(8 BYTE) NOT NULL 
	, PKG_TEMPLATE_ID VARCHAR2(10 BYTE) NOT NULL 
	, PKG_RULE_ID VARCHAR2(10 BYTE) NOT NULL 
	, SUPV_LVL_ID VARCHAR2(8 BYTE) NOT NULL 
	, INCLUDE_SALPLN_FLG VARCHAR2(1 BYTE) NOT NULL 
	, POSN_DATA_MESSAGE VARCHAR2(1 BYTE) NOT NULL 
	, HE_MED_OFF_IND VARCHAR2(1 BYTE) NOT NULL 
	, HE_SE_TYPE VARCHAR2(1 BYTE) NOT NULL 
	, HE_TERM_ID VARCHAR2(2 BYTE) NOT NULL 
	, HE_POS_SUBJECT_TO VARCHAR2(1 BYTE) NOT NULL 
	, HE_ACTIVITY_FUNC VARCHAR2(4 BYTE) NOT NULL 
	, HE_REASON_CODE VARCHAR2(1 BYTE) NOT NULL 
	, FUNCTION_CD VARCHAR2(2 BYTE) NOT NULL 
	, DESCRLONG LONG 
);

/

CREATE INDEX EHRP.PS_POSITION_DATA_IDX1 ON EHRP.PS_POSITION_DATA (POSITION_NBR ASC);
CREATE INDEX EHRP.PS_POSITION_DATA_IDX2 ON EHRP.PS_POSITION_DATA (BUSINESS_UNIT ASC, JOBCODE ASC);
CREATE INDEX EHRP.PS_POSITION_DATA_IDX3 ON EHRP.PS_POSITION_DATA (POSITION_NBR ASC, EFFDT ASC);
CREATE INDEX EHRP.PS_POSITION_DATA_IDX4 ON EHRP.PS_POSITION_DATA (JOBCODE ASC);
CREATE INDEX EHRP.PS_POSITION_DATA_IDX5 ON EHRP.PS_POSITION_DATA (EFF_STATUS ASC);

/




-------------------------------------
--PS_SAL_GRADE_TBL DDL
-------------------------------------
CREATE TABLE EHRP.PS_SAL_GRADE_TBL 
(
	SETID VARCHAR2(5 BYTE) NOT NULL 
	, SAL_ADMIN_PLAN VARCHAR2(4 BYTE) NOT NULL 
	, GRADE VARCHAR2(3 BYTE) NOT NULL 
	, EFFDT DATE NOT NULL 
	, EFF_STATUS VARCHAR2(1 BYTE) NOT NULL 
	, DESCR VARCHAR2(30 BYTE) NOT NULL 
	, DESCRSHORT VARCHAR2(10 BYTE) NOT NULL 
	, SALARY_MATRIX_CD VARCHAR2(5 BYTE) NOT NULL 
	, CURRENCY_CD VARCHAR2(3 BYTE) NOT NULL 
	, MIN_RT_HOURLY NUMBER(18, 6) NOT NULL 
	, MID_RT_HOURLY NUMBER(18, 6) NOT NULL 
	, MAX_RT_HOURLY NUMBER(18, 6) NOT NULL 
	, MIN_RT_MONTHLY NUMBER(18, 3) NOT NULL 
	, MID_RT_MONTHLY NUMBER(18, 3) NOT NULL 
	, MAX_RT_MONTHLY NUMBER(18, 3) NOT NULL 
	, MIN_RT_ANNUAL NUMBER(18, 3) NOT NULL 
	, MID_RT_ANNUAL NUMBER(18, 3) NOT NULL 
	, MAX_RT_ANNUAL NUMBER(18, 3) NOT NULL 
	, STEP_INCREM_TYPE VARCHAR2(1 BYTE) NOT NULL 
	, STEP_INCREM_ACCUM VARCHAR2(3 BYTE) NOT NULL 
	, MIN_RT_DAILY NUMBER(18, 3) NOT NULL 
	, MID_RT_DAILY NUMBER(18, 3) NOT NULL 
	, MAX_RT_DAILY NUMBER(18, 3) NOT NULL 
	, LABOR_AGREEMENT VARCHAR2(6 BYTE) NOT NULL 
	, EMPL_CTG VARCHAR2(6 BYTE) NOT NULL 
	, EMPL_CTG_L1 VARCHAR2(6 BYTE) NOT NULL 
	, EMPL_CTG_L2 VARCHAR2(6 BYTE) NOT NULL 
	, GVT_MAX_RT_BIWK NUMBER(9, 2) NOT NULL 
	, GVT_MID_RT_BIWK NUMBER(9, 2) NOT NULL 
	, GVT_MIN_RT_BIWK NUMBER(9, 2) NOT NULL 
	, GRADE_TITLE_JPN VARCHAR2(60 BYTE) NOT NULL 
	, MIN_YRS_GRADE NUMBER(*, 0) NOT NULL 
	, MAX_YRS_GRADE NUMBER(*, 0) NOT NULL 
	, MIN_GRD_AGE NUMBER(*, 0) NOT NULL 
	, REVIEW_COUNT NUMBER(*, 0) NOT NULL 
	, ELIGIBILITY_POINTS NUMBER(4, 1) NOT NULL 
	, REG_REGION VARCHAR2(5 BYTE) NOT NULL 
	, JOB_PROFILE_ID VARCHAR2(8 BYTE) NOT NULL 
);

/








--=============================================================================
-- VIEW simulated as table
--=============================================================================


-------------------------------------
--PS_HRS_LOCATION_I DDL
-------------------------------------
/*
CREATE VIEW EHRP.PS_HRS_LOCATION_I
AS 
SELECT 
	A.SETID,
	A.LOCATION,
	A.EFFDT,
	A.COUNTRY,
	A.STATE,
	A.DESCR,
	A.DESCRSHORT
FROM PS_LOCATION_TBL A;
*/
CREATE TABLE EHRP.PS_HRS_LOCATION_I
(
	SETID               VARCHAR2(5)
	, LOCATION          VARCHAR2(10)
	, EFFDT             DATE
	, COUNTRY           VARCHAR2(3)
	, STATE             VARCHAR2(6)
	, DESCR             VARCHAR2(30)
	, DESCRSHORT        VARCHAR2(10)
);

/




-------------------------------------
--PS_PERSONAL_DATA_VW DDL
-------------------------------------
/*
CREATE VIEW EHRP.PS_PERSONAL_DATA_VW
AS 
SELECT
	EMPLID,
	COUNTRY_NM_FORMAT,
	NAME,
	NAME_INITIALS,
	NAME_PREFIX,
	NAME_SUFFIX,
	NAME_ROYAL_PREFIX,
	NAME_ROYAL_SUFFIX,
	NAME_TITLE,
	LAST_NAME_SRCH,
	FIRST_NAME_SRCH,
	LAST_NAME,
	FIRST_NAME,
	MIDDLE_NAME,
	SECOND_LAST_NAME,
	SECOND_LAST_SRCH,
	NAME_AC,
	PREF_FIRST_NAME,
	PARTNER_LAST_NAME,
	PARTNER_ROY_PREFIX,
	LAST_NAME_PREF_NLD,
	NAME_DISPLAY,
	NAME_FORMAL,
	CAMPUS_ID,
	COUNTRY,
	ADDRESS1,
	ADDRESS2,
	ADDRESS3,
	ADDRESS4,
	CITY,
	NUM1,
	NUM2,
	HOUSE_TYPE,
	ADDR_FIELD1,
	ADDR_FIELD2,
	ADDR_FIELD3,
	COUNTY,
	STATE,
	POSTAL,
	GEO_CODE,
	IN_CITY_LIMIT,
	COUNTRY_OTHER,
	ADDRESS1_OTHER,
	ADDRESS2_OTHER,
	ADDRESS3_OTHER,
	ADDRESS4_OTHER,
	CITY_OTHER,
	COUNTY_OTHER,
	STATE_OTHER,
	POSTAL_OTHER,
	NUM1_OTHER,
	NUM2_OTHER,
	HOUSE_TYPE_OTHER,
	ADDR_FIELD1_OTHER,
	ADDR_FIELD2_OTHER,
	ADDR_FIELD3_OTHER,
	IN_CITY_LMT_OTHER,
	GEO_CODE_OTHER,
	COUNTRY_CODE,
	PHONE,
	EXTENSION,
	VA_BENEFIT,
	DEATH_CERTIF_NBR,
	FERPA,
	PLACE_OF_DEATH,
	US_WORK_ELIGIBILTY,
	MILITARY_STATUS,
	CITIZEN_PROOF1,
	CITIZEN_PROOF2,
	MEDICARE_ENTLD_DT,
	HONSEKI_JPN,
	MILITARY_STAT_ITA,
	MILITARY_TYPE_ITA,
	MILITARY_RANK_ITA,
	MILITARY_END_ITA,
	ENTRY_DT_FRA,
	MILIT_SITUATN_FRA,
	CPAMID,
	BILINGUALISM_CODE,
	HEALTH_CARE_NBR,
	HEALTH_CARE_STATE,
	MILIT_SITUATN_ESP,
	SOC_SEC_AFF_DT,
	MILITARY_STAT_GER,
	EXPCTD_MILITARY_DT,
	HR_RESPONSIBLE_ID,
	SMOKER,
	SMOKER_DT,
	GVT_CRED_MIL_SVCE,
	GVT_MILITARY_COMP,
	GVT_MIL_GRADE,
	GVT_MIL_RESRVE_CAT,
	GVT_MIL_SEP_RET,
	GVT_MIL_SVCE_END,
	GVT_MIL_SVCE_START,
	GVT_MIL_VERIFY,
	GVT_PAR_NBR_LAST,
	GVT_UNIF_SVC_CTR,
	GVT_VET_PREF_APPT,
	GVT_VET_PREF_RIF,
	GVT_CHANGE_FLAG,
	GVT_DRAFT_STATUS,
	GVT_YR_ATTAINED,
	-- DISABLED_VET,
	--DISABLED,
	-- GVT_DISABILITY_CD,
	GRADE,
	SAL_ADMIN_PLAN,
	GVT_CURR_AGCY_EMPL,
	GVT_CURR_FED_EMPL,
	GVT_HIGH_PAY_PLAN,
	GVT_HIGH_GRADE,
	GVT_PREV_AGCY_EMPL,
	GVT_PREV_FED_EMPL,
	GVT_SEP_INCENTIVE,
	GVT_SEP_INCENT_DT,
	GVT_TENURE,
	GVT_PAY_PLAN,
	BARG_UNIT,
	LASTUPDDTTM,
	-- SEX,
	--MAR_STATUS,
	--MAR_STATUS_DT,
	-- BIRTHDATE,
	BIRTHPLACE,
	BIRTHCOUNTRY,
	BIRTHSTATE,
	-- DT_OF_DEATH,
	HIGHEST_EDUC_LVL,
	FT_STUDENT,
	LANG_CD,
	ALTER_EMPLID,
	ADDRESS1_AC,
	ADDRESS2_AC,
	ADDRESS3_AC,
	CITY_AC,
	HE_ERI
FROM EHRP.PS_PERSONAL_DATA;
*/

CREATE TABLE EHRP.PS_PERSONAL_DATA_VW
(
	EMPLID                  VARCHAR2(11)
	, COUNTRY_NM_FORMAT     VARCHAR2(3)
	, NAME                  VARCHAR2(50)
	, NAME_INITIALS         VARCHAR2(6)
	, NAME_PREFIX           VARCHAR2(4)
	, NAME_SUFFIX           VARCHAR2(15)
	, NAME_ROYAL_PREFIX     VARCHAR2(15)
	, NAME_ROYAL_SUFFIX     VARCHAR2(15)
	, NAME_TITLE            VARCHAR2(30)
	, LAST_NAME_SRCH        VARCHAR2(30)
	, FIRST_NAME_SRCH       VARCHAR2(30)
	, LAST_NAME             VARCHAR2(30)
	, FIRST_NAME            VARCHAR2(30)
	, MIDDLE_NAME           VARCHAR2(30)
	, SECOND_LAST_NAME      VARCHAR2(30)
	, SECOND_LAST_SRCH      VARCHAR2(30)
	, NAME_AC               VARCHAR2(50)
	, PREF_FIRST_NAME       VARCHAR2(30)
	, PARTNER_LAST_NAME     VARCHAR2(30)
	, PARTNER_ROY_PREFIX    VARCHAR2(15)
	, LAST_NAME_PREF_NLD    VARCHAR2(1)
	, NAME_DISPLAY          VARCHAR2(50)
	, NAME_FORMAL           VARCHAR2(60)
	, CAMPUS_ID             VARCHAR2(16)
	, COUNTRY               VARCHAR2(3)
	, ADDRESS1              VARCHAR2(55)
	, ADDRESS2              VARCHAR2(55)
	, ADDRESS3              VARCHAR2(55)
	, ADDRESS4              VARCHAR2(55)
	, CITY                  VARCHAR2(30)
	, NUM1                  VARCHAR2(6)
	, NUM2                  VARCHAR2(6)
	, HOUSE_TYPE            VARCHAR2(2)
	, ADDR_FIELD1           VARCHAR2(2)
	, ADDR_FIELD2           VARCHAR2(4)
	, ADDR_FIELD3           VARCHAR2(4)
	, COUNTY                VARCHAR2(30)
	, STATE                 VARCHAR2(6)
	, POSTAL                VARCHAR2(12)
	, GEO_CODE              VARCHAR2(11)
	, IN_CITY_LIMIT         VARCHAR2(1)
	, COUNTRY_OTHER         VARCHAR2(3)
	, ADDRESS1_OTHER        VARCHAR2(55)
	, ADDRESS2_OTHER        VARCHAR2(55)
	, ADDRESS3_OTHER        VARCHAR2(55)
	, ADDRESS4_OTHER        VARCHAR2(55)
	, CITY_OTHER            VARCHAR2(30)
	, COUNTY_OTHER          VARCHAR2(30)
	, STATE_OTHER           VARCHAR2(6)
	, POSTAL_OTHER          VARCHAR2(12)
	, NUM1_OTHER            VARCHAR2(6)
	, NUM2_OTHER            VARCHAR2(6)
	, HOUSE_TYPE_OTHER      VARCHAR2(2)
	, ADDR_FIELD1_OTHER     VARCHAR2(2)
	, ADDR_FIELD2_OTHER     VARCHAR2(4)
	, ADDR_FIELD3_OTHER     VARCHAR2(4)
	, IN_CITY_LMT_OTHER     VARCHAR2(1)
	, GEO_CODE_OTHER        VARCHAR2(11)
	, COUNTRY_CODE          VARCHAR2(3)
	, PHONE                 VARCHAR2(24)
	, EXTENSION             VARCHAR2(6)
	, VA_BENEFIT            VARCHAR2(1)
	, DEATH_CERTIF_NBR      VARCHAR2(10)
	, FERPA                 VARCHAR2(1)
	, PLACE_OF_DEATH        VARCHAR2(30)
	, US_WORK_ELIGIBILTY    VARCHAR2(1)
	, MILITARY_STATUS       VARCHAR2(1)
	, CITIZEN_PROOF1        VARCHAR2(10)
	, CITIZEN_PROOF2        VARCHAR2(10)
	, MEDICARE_ENTLD_DT     DATE
	, HONSEKI_JPN           VARCHAR2(2)
	, MILITARY_STAT_ITA     VARCHAR2(1)
	, MILITARY_TYPE_ITA     VARCHAR2(2)
	, MILITARY_RANK_ITA     VARCHAR2(50)
	, MILITARY_END_ITA      DATE
	, ENTRY_DT_FRA          DATE
	, MILIT_SITUATN_FRA     VARCHAR2(3)
	, CPAMID                VARCHAR2(6)
	, BILINGUALISM_CODE     VARCHAR2(1)
	, HEALTH_CARE_NBR       VARCHAR2(12)
	, HEALTH_CARE_STATE     VARCHAR2(6)
	, MILIT_SITUATN_ESP     VARCHAR2(3)
	, SOC_SEC_AFF_DT        DATE
	, MILITARY_STAT_GER     VARCHAR2(1)
	, EXPCTD_MILITARY_DT    DATE
	, HR_RESPONSIBLE_ID     VARCHAR2(11)
	, SMOKER                VARCHAR2(1)
	, SMOKER_DT             DATE
	, GVT_CRED_MIL_SVCE     VARCHAR2(4)
	, GVT_MILITARY_COMP     VARCHAR2(1)
	, GVT_MIL_GRADE         VARCHAR2(3)
	, GVT_MIL_RESRVE_CAT    VARCHAR2(1)
	, GVT_MIL_SEP_RET       VARCHAR2(1)
	, GVT_MIL_SVCE_END      DATE
	, GVT_MIL_SVCE_START    DATE
	, GVT_MIL_VERIFY        VARCHAR2(1)
	, GVT_PAR_NBR_LAST      NUMBER(38)
	, GVT_UNIF_SVC_CTR      VARCHAR2(1)
	, GVT_VET_PREF_APPT     VARCHAR2(1)
	, GVT_VET_PREF_RIF      VARCHAR2(1)
	, GVT_CHANGE_FLAG       VARCHAR2(1)
	, GVT_DRAFT_STATUS      VARCHAR2(1)
	, GVT_YR_ATTAINED       DATE
	, GRADE                 VARCHAR2(3)
	, SAL_ADMIN_PLAN        VARCHAR2(4)
	, GVT_CURR_AGCY_EMPL    VARCHAR2(1)
	, GVT_CURR_FED_EMPL     VARCHAR2(1)
	, GVT_HIGH_PAY_PLAN     VARCHAR2(2)
	, GVT_HIGH_GRADE        VARCHAR2(3)
	, GVT_PREV_AGCY_EMPL    VARCHAR2(1)
	, GVT_PREV_FED_EMPL     VARCHAR2(1)
	, GVT_SEP_INCENTIVE     VARCHAR2(1)
	, GVT_SEP_INCENT_DT     DATE
	, GVT_TENURE            VARCHAR2(1)
	, GVT_PAY_PLAN          VARCHAR2(2)
	, BARG_UNIT             VARCHAR2(4)
	, LASTUPDDTTM           TIMESTAMP(6)
	, BIRTHPLACE            VARCHAR2(30)
	, BIRTHCOUNTRY          VARCHAR2(3)
	, BIRTHSTATE            VARCHAR2(6)
	, HIGHEST_EDUC_LVL      VARCHAR2(2)
	, FT_STUDENT            VARCHAR2(1)
	, LANG_CD               VARCHAR2(3)
	, ALTER_EMPLID          VARCHAR2(11)
	, ADDRESS1_AC           VARCHAR2(55)
	, ADDRESS2_AC           VARCHAR2(55)
	, ADDRESS3_AC           VARCHAR2(55)
	, CITY_AC               VARCHAR2(30)
	, HE_ERI                VARCHAR2(6)
);

/
 

