
----------------------------------
-- grant for HHS_HR_RW_ROLE
----------------------------------

GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.BATCH_JOB_EXECUTION TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.BATCH_JOB_EXECUTION_CONTEXT TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.BATCH_JOB_EXECUTION_PARAMS TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.BATCH_JOB_INSTANCE TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.BATCH_STEP_EXECUTION TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.BATCH_STEP_EXECUTION_CONTEXT TO HHS_HR_RW_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.ERROR_LOG TO HHS_HR_RW_ROLE;




----------------------------------
-- grant for HHS_HR_DEV_ROLE
----------------------------------

GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.BATCH_JOB_EXECUTION TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.BATCH_JOB_EXECUTION_CONTEXT TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.BATCH_JOB_EXECUTION_PARAMS TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.BATCH_JOB_INSTANCE TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.BATCH_STEP_EXECUTION TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.BATCH_STEP_EXECUTION_CONTEXT TO HHS_HR_DEV_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.ERROR_LOG TO HHS_HR_DEV_ROLE;


