
----------------------------------
-- grant for HHS_BIIS_VIEW_ROLE
----------------------------------
GRANT SELECT ON EHRP.PS_DEPT_TBL                TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON EHRP.PS_HE_EWIT_DEPT_1          TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON EHRP.PS_HE_RECRUIT_EWIT         TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON EHRP.PS_HRS_JO_LOC              TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON EHRP.PS_HRS_JO_NAME             TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON EHRP.PS_HRS_JO_POSN             TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON EHRP.PS_HRS_JO_RPL              TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON EHRP.PS_HRS_JO_RQMT             TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON EHRP.PS_HRS_JOB_OPENING         TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON EHRP.PS_JOBCODE_TBL             TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON EHRP.PS_POSITION_DATA           TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON EHRP.PS_JOBCODE_TBL             TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON EHRP.PS_SAL_GRADE_TBL           TO HHS_BIIS_VIEW_ROLE;


GRANT SELECT ON EHRP.PS_HRS_LOCATION_I          TO HHS_BIIS_VIEW_ROLE;
GRANT SELECT ON EHRP.PS_PERSONAL_DATA_VW        TO HHS_BIIS_VIEW_ROLE;




----------------------------------
-- grant for HHS_BIIS_EHRP_OWNER_ROLE
----------------------------------
GRANT DELETE, INSERT, SELECT, UPDATE ON EHRP.PS_DEPT_TBL                TO HHS_BIIS_EHRP_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON EHRP.PS_HE_EWIT_DEPT_1          TO HHS_BIIS_EHRP_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON EHRP.PS_HE_RECRUIT_EWIT         TO HHS_BIIS_EHRP_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON EHRP.PS_HRS_JO_LOC              TO HHS_BIIS_EHRP_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON EHRP.PS_HRS_JO_NAME             TO HHS_BIIS_EHRP_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON EHRP.PS_HRS_JO_POSN             TO HHS_BIIS_EHRP_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON EHRP.PS_HRS_JO_RPL              TO HHS_BIIS_EHRP_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON EHRP.PS_HRS_JO_RQMT             TO HHS_BIIS_EHRP_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON EHRP.PS_HRS_JOB_OPENING         TO HHS_BIIS_EHRP_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON EHRP.PS_JOBCODE_TBL             TO HHS_BIIS_EHRP_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON EHRP.PS_POSITION_DATA           TO HHS_BIIS_EHRP_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON EHRP.PS_SAL_GRADE_TBL           TO HHS_BIIS_EHRP_OWNER_ROLE;


GRANT DELETE, INSERT, SELECT, UPDATE ON EHRP.PS_HRS_LOCATION_I          TO HHS_BIIS_EHRP_OWNER_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON EHRP.PS_PERSONAL_DATA_VW        TO HHS_BIIS_EHRP_OWNER_ROLE;
