
----------------------------------
-- grant for HHS_HR_RW_ROLE
----------------------------------

GRANT EXECUTE ON HHS_HR.SP_TIME2STAFF_STG2FNL TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TIME2OFFER_STG2FNL TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_IHS_VAC_STG2FNL TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CDC_TIME2STAFF_STG2FNL TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CDC_TIME2OFFER_STG2FNL TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CDC_CERT_STG2FNL TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CDC_AUDIT_STG2FNL TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CDC_ANN_STG2FNL TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CMS_POSSESS_STG2FNL TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CMS_TIME2HIRE_STG2FNL TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CMS_REQUEST_STG2FNL TO HHS_HR_RW_ROLE;

----------------------------------
-- grant for HHS_HR_DEV_ROLE
----------------------------------

GRANT EXECUTE ON HHS_HR.SP_TIME2STAFF_STG2FNL TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_TIME2OFFER_STG2FNL TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_IHS_VAC_STG2FNL TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CDC_TIME2STAFF_STG2FNL TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CDC_TIME2OFFER_STG2FNL TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CDC_CERT_STG2FNL TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CDC_AUDIT_STG2FNL TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CDC_ANN_STG2FNL TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CMS_POSSESS_STG2FNL TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CMS_TIME2HIRE_STG2FNL TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_HR.SP_CMS_REQUEST_STG2FNL TO HHS_HR_DEV_ROLE;