--Alter table HHS_HR.PS_POSITION_DATA
ALTER TABLE HHS_HR.PS_POSITION_DATA
DROP COLUMN JOB_PROFILE_ID;

--Alter table HHS_HR.PS_JOBCODE_TBL
ALTER TABLE HHS_HR.PS_JOBCODE_TBL
DROP COLUMN JOB_PROFILE_ID;

--Alter table HHS_HR.PS_SAL_GRADE_TBL
ALTER TABLE HHS_HR.PS_SAL_GRADE_TBL
DROP COLUMN JOB_PROFILE_ID;

--Alter table HHS_HR.PS_GVT_EMPLOYMENT
ALTER TABLE HHS_HR.PS_GVT_EMPLOYMENT
DROP COLUMN GVT_SEC_CLR_STATUS;

--Alter table HHS_HR.PS_GVT_EMPLOYMENT
ALTER TABLE HHS_HR.PS_GVT_EMPLOYMENT
DROP COLUMN GVT_CLRNCE_STAT_DT;

--Alter table HHS_HR.PS_GVT_EMPLOYMENT
ALTER TABLE HHS_HR.PS_GVT_EMPLOYMENT
DROP COLUMN SECURITY_CLEARANCE;

--Alter table HHS_HR.PS_PERSONAL_DATA_VW 
ALTER TABLE HHS_HR.PS_PERSONAL_DATA_VW
DROP COLUMN HE_ERI;