--PS_POSITION_DATA permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_HR.PS_POSITION_DATA TO HHS_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_HR.PS_POSITION_DATA TO HHS_HR_DEV_ROLE;
GRANT SELECT ON HHS_HR.PS_POSITION_DATA TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_POSITION_DATA TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT ON HHS_HR.PS_POSITION_DATA TO HHS_CDC_HR_DEV_ROLE;

--PS_JOBCODE_TBL permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_HR.PS_JOBCODE_TBL TO HHS_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_HR.PS_JOBCODE_TBL TO HHS_HR_DEV_ROLE;
GRANT SELECT ON HHS_HR.PS_JOBCODE_TBL TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_JOBCODE_TBL TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT ON HHS_HR.PS_JOBCODE_TBL TO HHS_CDC_HR_DEV_ROLE;

--PS_SAL_GRADE_TBL permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_HR.PS_SAL_GRADE_TBL TO HHS_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_HR.PS_SAL_GRADE_TBL TO HHS_HR_DEV_ROLE;
GRANT SELECT ON HHS_HR.PS_SAL_GRADE_TBL TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_SAL_GRADE_TBL TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT ON HHS_HR.PS_SAL_GRADE_TBL TO HHS_CDC_HR_DEV_ROLE;

--PS_GVT_EMPLOYMENT permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_HR.PS_GVT_EMPLOYMENT TO HHS_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_HR.PS_GVT_EMPLOYMENT TO HHS_HR_DEV_ROLE;
GRANT SELECT ON HHS_HR.PS_GVT_EMPLOYMENT TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_GVT_EMPLOYMENT TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT ON HHS_HR.PS_GVT_EMPLOYMENT TO HHS_CDC_HR_DEV_ROLE;

--PS_PERSONAL_DATA_VW permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_HR.PS_PERSONAL_DATA_VW TO HHS_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_HR.PS_PERSONAL_DATA_VW TO HHS_HR_DEV_ROLE;
GRANT SELECT ON HHS_HR.PS_PERSONAL_DATA_VW TO HHS_WHRSC_HR;
GRANT SELECT ON HHS_HR.PS_PERSONAL_DATA_VW TO HHS_CDC_HR_RW_ROLE;
GRANT SELECT ON HHS_HR.PS_PERSONAL_DATA_VW TO HHS_CDC_HR_DEV_ROLE;
