
----------------------------------
-- grant for HHS_HR_RW_ROLE
----------------------------------
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.PS_GVT_EMPLOYMENT TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.PS_GVT_JOB TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.PS_EMPLOYEE_REVIEW TO HHS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.PS_GVT_PAR_REMARKS TO HHS_HR_RW_ROLE;


----------------------------------
-- grant for HHS_HR_DEV_ROLE
----------------------------------
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.PS_GVT_EMPLOYMENT TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.PS_GVT_JOB TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.PS_EMPLOYEE_REVIEW TO HHS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_HR.PS_GVT_PAR_REMARKS TO HHS_HR_DEV_ROLE;

