CREATE INDEX ADMINISTRATIVE_CODE_IDX1 ON HHS_HR.ADMINISTRATIVE_CODE (OPDIV, ADMIN_CODE, ADMIN_CODE_DESC);
CREATE INDEX EMPLOYEE_LOOKUP_IDX2 ON HHS_HR.EMPLOYEE_LOOKUP (OPDIV, UPPER(FULL_NAME), ORG_CD);
